const app=document.querySelector("#app"), $=s=>document.querySelector(s);
let books=[],book=null,current=null,state=null;
const esc=s=>(s??"").toString().replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const stateKey=id=>`bd_${id}_full`, collectionKey="bd_coleccion_v14", journalKey="bd_cuaderno_v15";
function loadState(id){const legacy=id==="congregados"?localStorage.getItem("bd_congregados_full"):null;return JSON.parse(localStorage.getItem(stateKey(id))||legacy||'{"done":{},"read":{},"test":{},"disc":{},"last":""}');}
function save(){if(book&&state)localStorage.setItem(stateKey(book.id),JSON.stringify(state))}
function loadCollection(){try{return JSON.parse(localStorage.getItem(collectionKey)||"[]")}catch{return []}}
function saveCollection(x){localStorage.setItem(collectionKey,JSON.stringify(x))}
function loadJournal(){try{return JSON.parse(localStorage.getItem(journalKey)||"[]")}catch{return []}}
function saveJournal(x){localStorage.setItem(journalKey,JSON.stringify(x))}
function sectionLabel(b,sid){let q=b.secciones.find(x=>x.id===sid);return q?`${q.tipo} · ${q.titulo}`:sid}
function lastDoneDate(){let j=loadJournal();return j.length?j[0].date:null}
const ADMIN_MODE_KEY='ministerio_admin_mode_v23';
function isAdminMode(){return localStorage.getItem(ADMIN_MODE_KEY)==='1'}
window.toggleAdminMode=()=>{if(isAdminMode()){localStorage.removeItem(ADMIN_MODE_KEY);syncAdminUI();alert('Modo visitante activado.');ministryHome()}else{openAdminAccess()}}
window.openAdminAccess=()=>{document.getElementById('adminAccessModal')?.remove();let box=document.createElement('div');box.id='adminAccessModal';box.className='adminAccessOverlay';box.innerHTML=`<div class="adminAccessCard"><button class="adminClose" onclick="closeAdminAccess()">×</button><span class="badge">🔐 ADMINISTRACIÓN</span><h2>Acceso de administración</h2><p>Ingrese su clave para administrar Videos y Recursos.</p><input id="adminPin" type="password" inputmode="numeric" placeholder="Clave de administración" onkeydown="if(event.key==='Enter')confirmAdminAccess()"><button class="btn adminEnter" onclick="confirmAdminAccess()">Entrar</button><small>La vista pública permanece en modo visitante.</small></div>`;document.body.appendChild(box);setTimeout(()=>document.getElementById('adminPin')?.focus(),30)}
window.closeAdminAccess=()=>document.getElementById('adminAccessModal')?.remove()
window.confirmAdminAccess=()=>{let pin=document.getElementById('adminPin')?.value||'';if(pin==='2026'){localStorage.setItem(ADMIN_MODE_KEY,'1');closeAdminAccess();syncAdminUI();ministryHome()}else{alert('Clave incorrecta.');document.getElementById('adminPin')?.select()}}

function enforceVisitorPermissions(){
 if(isAdminMode())return;
 document.querySelectorAll('.videoAddBtn,.resourceAddBtn,.resourceDelete').forEach(e=>e.remove());
 document.querySelectorAll('button').forEach(b=>{
   const t=(b.textContent||'').toLowerCase();
   if(t.includes('agregar video')||t.includes('agregar recurso')||t.includes('eliminar video')||t.trim()==='🗑 eliminar') b.remove();
 });
}
window.syncAdminUI=()=>{let b=document.getElementById('adminTopBtn');if(!b)return;if(isAdminMode()){b.textContent='⚙ Administrador · Salir';b.classList.add('active')}else{b.textContent='🔐 Administrar';b.classList.remove('active')}}
fetch("data/biblioteca.json").then(r=>r.json()).then(d=>{books=d;ministryHome()}).catch(()=>app.innerHTML='<div class="card">Abra la aplicación con <b>Go Live</b>.</div>');

function ministryHome(){
 book=null;current=null;syncAdminUI();
 const name=profileName();
 const first=books[0], second=books[1];
 app.innerHTML=`
 <section class="minHero">
  <div class="minGlow"></div><div class="minMountains"></div>
  <div class="minHeroCopy"><div class="minEyebrow">UNA BIBLIOTECA PARA</div><h1>VIVIR LA PALABRA</h1><div class="minSteps">Lee <i></i> Comprende <i></i> Enseña <i></i> Vive</div><p>Enseñanzas, libros, recursos y herramientas para profundizar en la Palabra, examinar la vida y formar una generación que conozca y viva a Cristo.</p><div class="minCtas"><button class="btn minPrimary" onclick="library()">▣ Entrar a la Biblioteca ›</button><button class="btn minSecondary" onclick="teachings()">▷ Ver enseñanza ›</button></div></div>
  <div class="minVerse"><em>“Toda la Escritura es inspirada por Dios<br>y útil para enseñar, para redargüir, para corregir,<br>para instruir en justicia.”</em><b>▣ 2 Timoteo 3:16</b></div><div class="minBible">SANTA<br>BIBLIA</div>
 </section>
 <section class="minNavGrid"><button onclick="teachings()"><b>▣</b><span><strong>Enseñanzas</strong><small>Temas para la vida</small></span></button><button onclick="library()"><b>▤</b><span><strong>Biblioteca</strong><small>Todos los libros</small></span></button><button onclick="dailyPill()"><b>💡</b><span><strong>Píldoras</strong><small>Verdades en breve</small></span></button><button onclick="videosPage()"><b>▷</b><span><strong>Videos</strong><small>Mensajes y recursos</small></span></button><button onclick="resourcesPage()"><b>▧</b><span><strong>Recursos</strong><small>Herramientas prácticas</small></span></button><button onclick="contactPage()"><b>♟</b><span><strong>Contacto</strong><small>Conversemos</small></span></button></section>
 <section class="minFeatureGrid">
  <article class="featureCard teachingFeature"><div><span>Enseñanza<br>destacada</span><i></i><h2>Dios no comenzó<br>con un templo</h2><p>Enseñanza extraída de CONGREGADOS: Dios comenzó formando una relación.</p><button onclick="teachings()">Ver enseñanza ›</button></div></article>
  <article class="featureCard pillFeature"><div class="featureText"><div class="featureTitle">🌱 <b>Píldora de hoy</b></div><small>CONGREGADOS</small><p>La verdadera congregación comienza con un corazón que reconoce a Cristo.</p><b>Mateo 18:20</b><button onclick="dailyPill()">Ver píldora ›</button></div><div class="prayerVisual">🙏</div></article>
  <article class="featureCard booksFeature"><h2>Nuestros libros</h2><p>Enseñanzas para vivir la Palabra</p><div class="miniCovers">${first?`<img src="${first.portada}" alt="${esc(first.titulo)}">`:''}${second?`<img src="${second.portada}" alt="${esc(second.titulo)}">`:''}<div class="coming">PRÓXIMAMENTE</div></div><button onclick="library()">Ver todos los libros ›</button></article>
  <article class="featureCard smallFeature"><b>↗</b><div><h2>Serie de formación</h2><p>Recorridos temáticos para profundizar en la Palabra y aplicarla en la vida.</p><button onclick="formation()">Explorar series ›</button></div></article>
  <article class="featureCard smallFeature"><b>▷</b><div><h2>Videos</h2><p>Mensajes, enseñanzas y recursos en video para tu crecimiento.</p><button onclick="videosPage()">Ver videos ›</button></div></article>
  <article class="featureCard smallFeature"><b>▧</b><div><h2>Recursos prácticos</h2><p>Guías, formatos y herramientas para aplicar la Palabra.</p><button onclick="resourcesPage()">Ver recursos ›</button></div></article>
 </section>
 <div class="minMotto"><span></span><em>“La verdad de la Palabra, aplicada en la vida, transforma generaciones.”</em><span></span><b>Leonard Moon</b></div><div class="adminModeEntry"><button onclick="toggleAdminMode()">${isAdminMode()?'⚙ Salir de administración':'⚙ Administración'}</button><small>${isAdminMode()?'Modo administrador activo':'Vista pública del Ministerio'}</small></div>`;
}
window.ministryHome=ministryHome;
function simpleMinistryPage(icon,title,subtitle,body){app.innerHTML=`<section class="ministryPage"><button class="btn secondary" onclick="ministryHome()">← Inicio</button><div class="pageIcon">${icon}</div><h1>${title}</h1><p class="lead">${subtitle}</p>${body}</section>`}
// v1.9: teachings se define al final desde el contenido real de los libros.
window.dailyPill=()=>{if(books[0])pills(books[0].id);else ministryHome()};
window.videosPage=()=>simpleMinistryPage('▷','Videos','Mensajes y enseñanzas en video.',`<div class="emptyMinistry"><h2>Próximamente</h2><p>Este espacio queda preparado para incorporar los videos del ministerio sin alterar la Biblioteca Digital.</p></div>`);
window.resourcesPage=()=>{resourceFilter='todos';ministryResources=[...publicResources,...loadLocalResources().filter(l=>!publicResources.some(p=>p.id===l.id))];app.innerHTML=`<section class="resourceHero"><div><span class="badge">📄 RECURSOS</span><h1>Herramientas para profundizar y llevar la enseñanza a la vida.</h1><p>Guías, estudios, plantillas y materiales prácticos para crecer, enseñar y aplicar la Palabra en la vida diaria.</p>${isAdminMode()?`<button class="btn resourceAddBtn" onclick="openResourceUploader()">＋ Agregar recurso</button>`:''}</div></section><section class="resourceToolbar"><input id="resourceSearch" placeholder="Buscar recursos..." oninput="renderResources()"><div id="resourceFilters"></div></section><div id="resourceResults"></div>`;renderResources();enforceVisitorPermissions()}
window.setResourceFilter=(el,c)=>{resourceFilter=c;renderResources();enforceVisitorPermissions()}
window.renderResources=()=>{let filters=document.getElementById('resourceFilters');if(filters)filters.innerHTML=resourceCats().map(c=>`<button class="resourceFilter ${resourceFilter===c?'active':''}" onclick="setResourceFilter(this,'${String(c).replace(/'/g,"\\'")}')">${c==='todos'?'Todos':esc(c)}</button>`).join('');let q=(document.getElementById('resourceSearch')?.value||'').trim().toLowerCase();let rows=ministryResources.filter(r=>(resourceFilter==='todos'||r.categoria===resourceFilter)&&(!q||`${r.titulo||''} ${r.descripcion||''} ${r.libro||''}`.toLowerCase().includes(q)));let host=document.getElementById('resourceResults');if(!host)return;if(!ministryResources.length){host.innerHTML=`<section class="resourceEmpty"><div class="resourceEmptyIcon">📄</div><h2>La Biblioteca de Recursos está lista</h2><p>Aquí puede incorporar los PDF que quiera poner a disposición de quienes visiten el Ministerio.</p><button class="btn" onclick="openResourceUploader()">＋ Agregar mi primer recurso</button></section>`;return}let featured=rows.find(r=>r.destacado)||rows[0],rest=rows.filter(r=>!featured||r.id!==featured.id);host.innerHTML=`${featured?`<section class="resourceFeatured"><h2>☆ Recurso destacado</h2><article><div class="resourceCover">📄<b>PDF</b></div><div class="resourceInfo"><span class="resourceTag">${esc(featured.categoria||'Recurso')}</span><h3>${esc(featured.titulo)}</h3>${featured.libro?`<small>Relacionado con: ${esc(featured.libro)}</small>`:''}<p>${esc(featured.descripcion||'')}</p><div class="resourceMeta">${featured.fecha?`📅 ${esc(featured.fecha)}`:''}${featured.tamano?` <span>·</span> 📄 ${esc(featured.tamano)}`:''}</div></div><div class="resourceActions"><button class="btn" onclick="viewResource('${featured.id}')">👁 Ver en línea</button><button class="btn secondary" onclick="downloadResource('${featured.id}')">⇩ Descargar</button>${isAdminMode()?`<button class="btn danger" onclick="deleteResource('${featured.id}')">🗑 Eliminar</button>`:''}</div></article></section>`:''}<section class="resourceList"><div class="resourceListHead"><h2>▣ Más recursos</h2><span>${rows.length} recurso${rows.length===1?'':'s'}</span></div><div class="resourceGrid">${rest.map(r=>`<article class="resourceCard"><div class="resourceCardTop"><span>📄</span><b>PDF</b></div><span class="resourceTag">${esc(r.categoria||'Recurso')}</span><h3>${esc(r.titulo)}</h3>${r.libro?`<small>Relacionado con:<br>${esc(r.libro)}</small>`:''}<p>${esc(r.descripcion||'')}</p><div class="resourceCardActions"><button class="btn secondary" onclick="viewResource('${r.id}')">👁 Ver</button><button class="btn secondary" onclick="downloadResource('${r.id}')">⇩ Descargar</button><button class="resourceDelete" onclick="deleteResource('${r.id}')">🗑</button></div></article>`).join('')}</div></section>`}
window.openResourceUploader=()=>{if(!isAdminMode()){alert('Esta función está disponible únicamente en modo administrador.');return}app.innerHTML=`<section class="resourceUploadPage"><button class="btn secondary" onclick="resourcesPage()">← Volver a Recursos</button><div class="resourceUploadCard"><span class="badge">📄 NUEVO RECURSO</span><h1>Agregar recurso PDF</h1><p>Seleccione el material terminado y complete sus datos.</p><label>Archivo PDF<input id="ruFile" type="file" accept="application/pdf,.pdf"></label><label>Título<input id="ruTitle" placeholder="Título del recurso"></label><div class="resourceFormGrid"><label>Categoría<select id="ruCat"><option>Guía</option><option>Estudio</option><option>Familia</option><option>Finanzas</option><option>Formación</option><option>Plantilla</option><option>Otro</option></select></label><label>Libro relacionado (opcional)<input id="ruBook"></label></div><label>Descripción<textarea id="ruDesc" rows="4"></textarea></label><div class="resourceFormGrid"><label>Fecha<input id="ruDate" type="date"></label><label class="checkLine"><input id="ruFeatured" type="checkbox"> Marcar como recurso destacado</label></div><div class="resourceUploadNotice"><b>Prueba local:</b> el PDF queda guardado en este navegador/equipo.</div><button class="btn" onclick="saveUploadedResource()">Guardar recurso</button></div></section>`}
window.saveUploadedResource=()=>{let file=document.getElementById('ruFile')?.files?.[0],title=(document.getElementById('ruTitle')?.value||'').trim();if(!file)return alert('Seleccione primero un archivo PDF.');if(!title)return alert('Escriba el título del recurso.');if(file.size>4.5*1024*1024)return alert('Para esta prueba local use un PDF de hasta 4,5 MB.');let rd=new FileReader();rd.onload=()=>{let r={id:'res-'+Date.now(),titulo:title,categoria:document.getElementById('ruCat').value,libro:document.getElementById('ruBook').value,descripcion:document.getElementById('ruDesc').value,fecha:document.getElementById('ruDate').value,destacado:document.getElementById('ruFeatured').checked,tamano:(file.size/1024/1024).toFixed(2)+' MB',archivo:rd.result,nombre:file.name};let all=loadLocalResources();if(r.destacado)all.forEach(x=>x.destacado=false);all.push(r);ministryResources=all;try{saveLocalResources();resourcesPage()}catch(e){alert('El navegador no tiene espacio suficiente para guardar este PDF.')}};rd.readAsDataURL(file)}
function findResourceById(id){return ministryResources.find(x=>x.id===id)||publicResources.find(x=>x.id===id)||loadLocalResources().find(x=>x.id===id)}
window.viewResource=id=>{let r=findResourceById(id);if(!r)return alert('El recurso no está disponible.');let source=r.archivo||r.url;if(!source)return alert('El archivo no está disponible.');window.open(source,'_blank')}
window.downloadResource=id=>{let r=findResourceById(id);if(!r)return alert('El recurso no está disponible.');let source=r.archivo||r.url;if(!source)return alert('El archivo no está disponible.');let a=document.createElement('a');a.href=source;a.download=r.nombre||((r.titulo||'recurso')+'.pdf');a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove()}
window.deleteResource=id=>{if(!isAdminMode()){alert('Esta función está disponible únicamente en modo administrador.');return}if(!confirm('¿Eliminar este recurso?'))return;ministryResources=loadLocalResources().filter(x=>x.id!==id);saveLocalResources();resourcesPage()}
window.contactPage=()=>{app.innerHTML=`<section class="contactHero"><div><span class="badge">💬 CONTACTO</span><h1>Conversemos</h1><h2>La Palabra también nos lleva a caminar acompañados.</h2><p>Si una enseñanza te ayudó, tienes una inquietud o deseas comunicarte con nosotros, este espacio está para escucharte.</p></div><div class="contactVerse"><em>“Llevad los unos las cargas de los otros, y cumplid así la ley de Cristo.”</em><b>Gálatas 6:2</b></div></section><section class="contactPaths"><button onclick="focusContact('Mensaje general')">💬 <b>Quiero escribirles</b><small>Para enviar un mensaje al Ministerio.</small></button><button onclick="focusContact('Petición de oración')">🙏 <b>Quiero compartir una petición de oración</b><small>Puedes contarnos tu necesidad.</small></button><button onclick="focusContact('Pregunta sobre una enseñanza')">📖 <b>Tengo una pregunta sobre una enseñanza</b><small>Cuéntanos tu inquietud.</small></button><button onclick="focusContact('Quiero mantenerme conectado')">👥 <b>Quiero mantenerme conectado</b><small>Para recibir nuevos contenidos.</small></button></section><section class="contactMain"><div class="contactFormCard"><h2>✉ Envíanos tu mensaje</h2><label>Nombre (opcional)<input id="ctName"></label><label>¿Sobre qué deseas escribirnos?<select id="ctTopic"><option>Mensaje general</option><option>Petición de oración</option><option>Pregunta sobre una enseñanza</option><option>Quiero mantenerme conectado</option></select></label><label>Medio de contacto (opcional)<input id="ctValue" placeholder="WhatsApp o correo"></label><label>Mensaje<textarea id="ctMessage" rows="7"></textarea></label><div class="contactButtons"><button class="btn" onclick="prepareContactMessage()">➤ Preparar mensaje</button><button class="btn secondary" onclick="clearContactForm()">↻ Limpiar</button></div><p id="ctStatus"></p></div><aside class="contactAside"><div class="contactBox"><h2>💬 Canales de contacto</h2><p>WhatsApp, correo y redes se configurarán antes de publicar el Portal.</p></div><div class="contactPrayer"><h2>🤎 Un espacio para orar juntos</h2><p>Las peticiones de oración serán tratadas con respeto y confidencialidad.</p></div><div class="contactPrivacy"><h2>🛡 Tu información merece cuidado</h2><p>Solo utilizaremos la información compartida para responder a la comunicación solicitada.</p></div></aside></section>`}
window.focusContact=topic=>{let t=document.getElementById('ctTopic');if(t)t.value=topic;document.getElementById('ctMessage')?.focus();document.querySelector('.contactFormCard')?.scrollIntoView({behavior:'smooth'})}
window.clearContactForm=()=>{['ctName','ctValue','ctMessage'].forEach(id=>{let e=document.getElementById(id);if(e)e.value=''});let st=document.getElementById('ctStatus');if(st)st.textContent=''}
window.prepareContactMessage=()=>{let msg=(document.getElementById('ctMessage')?.value||'').trim();if(!msg)return alert('Escribe primero tu mensaje.');let topic=document.getElementById('ctTopic')?.value||'Mensaje general',name=(document.getElementById('ctName')?.value||'').trim(),value=(document.getElementById('ctValue')?.value||'').trim();let text=`MINISTERIO DIGITAL — ${topic}\n\n${name?'Nombre: '+name+'\n':''}${value?'Contacto: '+value+'\n':''}\n${msg}`;navigator.clipboard?.writeText(text);let st=document.getElementById('ctStatus');if(st)st.textContent='✓ Mensaje preparado. Los canales oficiales se conectarán antes de publicar.'}

function bookPercent(b){
 let s=loadState(b.id), total=b.secciones.length||1;
 // El avance principal mide lectura real. Una sección totalmente terminada también cuenta como leída.
 let read=b.secciones.filter(sec=>(s.read&&s.read[sec.id])||(s.done&&s.done[sec.id])).length;
 return Math.round(read/total*100)
}
function percent(){return bookPercent(book)}
function library(){
 book=null;current=null;
 const name=profileName();
 const desc={
  "congregados":"Una invitación a volver al diseño de Dios para el hogar, donde Cristo es la cabeza y su voz guía cada área de la vida familiar.",
  "hombre-altar":"Una enseñanza para formar hombres y mujeres que, desde la intimidad con Dios, impacten su hogar, su entorno y su generación."
 };
 const tags=b=>(b.categoria||"").split("·").map(x=>x.trim()).filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join("");
 app.innerHTML=`
 <section class="landingHero">
   <div class="heroSun"></div><div class="heroHills h1x"></div><div class="heroHills h2x"></div>
   <div class="heroCopy">
     <div class="heroEyebrow">UNA BIBLIOTECA PARA</div>
     <h1>VIVIR LA PALABRA</h1>
     <div class="heroSteps"><span>Lee</span><i></i><span>Comprende</span><i></i><span>Enseña</span><i></i><span>Vive</span></div>
     <p>Un espacio para profundizar en la <b>Palabra</b>, examinar la vida y convertir cada enseñanza en un paso de formación en Cristo.</p>
   </div>
   <div class="heroVerse"><em>“Toda la Escritura es inspirada por Dios<br>y útil para enseñar, para redargüir, para corregir,<br>para instruir en justicia.”</em><strong>📖 2 Timoteo 3:16</strong></div>
   <div class="heroBible">SANTA<br>BIBLIA</div>
 </section>
 <section class="welcomeStrip">${name?`<div><span>☀️</span><p><b>Buenos días, ${esc(name)}</b><small>Continúa tu camino de formación.</small></p></div>`:`<div><span>📖</span><p><b>Bienvenido a tu Biblioteca Digital</b><small>Lee, comprende, enseña y vive la Palabra.</small></p></div>`}<button class="softTopBtn" onclick="profileBackup()">♙ Mi perfil</button></section>
 <section class="homeActions">
   <button class="actionTile active" onclick="library()"><b>📖</b><span><strong>Toda la biblioteca</strong><small>Explora todos los libros</small></span></button>
   <button class="actionTile" onclick="searchLibrary()"><b>⌕</b><span><strong>Buscar</strong><small>Encuentra un tema</small></span></button>
   <button class="actionTile" onclick="collection()"><b>♥</b><span><strong>Mi colección</strong><small>Píldoras y enseñanzas</small></span></button>
   <button class="actionTile" onclick="formation()"><b>🌱</b><span><strong>Mi camino de formación</strong><small>Tu progreso y aprendizaje</small></span></button>
   <button class="actionTile" onclick="profileBackup()"><b>♙</b><span><strong>Mi perfil y respaldo</strong><small>Tu nombre, exportar e importar</small></span></button>
 </section>
 <div class="libraryTitleRow"><div><h2>Mis libros disponibles</h2><i></i></div><p>📖 Tu biblioteca seguirá creciendo<br>con nuevos libros de Leonard Moon.</p></div>
 <section class="books elegantBooks">${books.map(b=>{const pct=bookPercent(b);return `<article class="bookCard elegantBook"><img class="cover" src="${b.portada}" alt="Portada ${esc(b.titulo)}"><div class="bookInfo"><div class="tagRow">${tags(b)}</div><h2>${esc(b.titulo)}</h2><h3>${esc(b.subtitulo)}</h3><p class="bookDescription">${esc(desc[b.id]||'Una enseñanza para profundizar, comprender y llevar la Palabra a la vida.')}</p><p class="muted authorLine">${esc(b.autor)}</p><div class="progressLine"><div class="progress"><i style="width:${pct}%"></i></div><b>${pct}% leído</b></div><div class="bookButtons"><button class="btn" onclick="selectBook('${b.id}')">📖 ${pct?'Continuar leyendo':'Abrir libro'}</button><button class="btn secondary" onclick="selectBook('${b.id}');setTimeout(openBook,0)">☷ Ver contenido</button></div></div></article>`}).join("")}</section>
 <section class="learningStrip"><button onclick="searchLibrary()"><b>📖</b><span><strong>Comprende</strong><small>Respuestas para tu vida</small></span><i>›</i></button><button onclick="formation()"><b>◉</b><span><strong>Discierne</strong><small>Principios que iluminan</small></span><i>›</i></button><button onclick="collection()"><b>💡</b><span><strong>Enseña</strong><small>Píldoras que transforman</small></span><i>›</i></button><button onclick="collection()"><b>↗</b><span><strong>Vive</strong><small>Lleva la verdad más lejos</small></span><i>›</i></button></section>
 <div class="closingMotto"><span></span><em>“La verdad de la Palabra, aplicada en la vida, transforma generaciones.”</em><span></span></div>`
}

window.selectBook=id=>{book=books.find(b=>b.id===id);state=loadState(id);home()}
function home(){app.innerHTML=`<section class="hero"><img class="cover" src="${book.portada}"><div><span class="badge">LIBRO COMPLETO</span><h1>${esc(book.titulo)}</h1><h2>${esc(book.subtitulo)}</h2><p class="muted">${esc(book.autor)}</p><div class="progress"><i style="width:${percent()}%"></i></div><p>${percent()}% del libro leído</p><div class="row"><button class="btn" onclick="openBook()">Índice del libro</button><button class="btn secondary" onclick="formation()">🌿 Mi camino de formación</button>${state.last?`<button class="btn secondary" onclick="openSection('${state.last}')">Continuar leyendo</button>`:""}<button class="btn secondary" onclick="pills('${book.id}')">💡 Píldoras</button><button class="btn secondary" onclick="library()">← Biblioteca</button></div></div></section><section class="card section"><h2>Experiencia del libro</h2><p>Lectura → comprensión → discernimiento → cierre → progreso. Ahora también puede guardar enseñanzas, consultar píldoras y compartir contenido.</p></section>`}
window.library=library;
window.openBook=()=>{app.innerHTML=`<section class="card"><div class="row"><button class="btn secondary" onclick="library()">← Biblioteca</button><button class="btn secondary" onclick="home()">Portada del libro</button><button class="btn secondary" onclick="pills('${book.id}')">💡 Píldoras</button></div><h1>${esc(book.titulo)}</h1><h2>Índice completo</h2>${book.secciones.map(s=>`<div class="chapter"><div><span class="badge">${esc(s.tipo)}</span><h3>${esc(s.titulo)}</h3><div class="muted">${esc(s.subtitulo)}</div></div><button class="btn ${state.done[s.id]?'secondary':''}" onclick="openSection('${s.id}')">${state.done[s.id]?'✓ Completado':'Abrir'}</button></div>`).join("")}</section>`}
function itemButton(type,text,label){return `<button class="mini" onclick='saveItem(${JSON.stringify(type)},${JSON.stringify(text)},${JSON.stringify(label)})'>♡ Guardar</button>`}
window.openSection=id=>{current=book.secciones.find(s=>s.id===id);state.last=id;save();app.innerHTML=`<article class="card reader"><div class="row"><button class="btn secondary" onclick="openBook()">← Índice</button><button class="btn secondary" onclick="pills('${book.id}','${current.id}')">💡 Píldoras de esta sección</button></div><span class="badge">${esc(current.tipo)}</span><h1>${esc(current.titulo)}</h1><h2>${esc(current.subtitulo)}</h2>${current.referencia?`<div class="quote scripture">📖 ${esc(current.referencia)}<br>${esc(current.versiculo)}<div>${itemButton('Porción bíblica',`${current.referencia} — ${current.versiculo}`,current.titulo)}</div></div>`:""}${current.secciones.map(renderSection).join("")}<div class="row section"><button class="btn" onclick="finishReading()">✓ Terminé la lectura</button><button class="btn secondary" onclick="openBook()">Índice</button></div></article>`}
function renderSection(s){const residuos=new Set(["Principio del formulario","Final del formulario"]);let h=s.heading?`<div class="head">${esc(s.heading)}</div>`:"";return h+s.lines.filter(x=>!residuos.has((x||"").trim())).map(x=>{if(x.startsWith("💬"))return `<div class="quote">${esc(x)}<div>${itemButton('Frase',x,current.titulo)}</div></div>`;if(x.startsWith("📖")||x.startsWith("✨"))return `<p><b>${esc(x)}</b> ${itemButton(x.startsWith('📖')?'Porción bíblica':'Frase',x,current.titulo)}</p>`;return `<p>${esc(x)}</p>`}).join("")}
window.finishReading=()=>{state.read=state.read||{};state.read[current.id]=true;save();experience()}
function experience(){app.innerHTML=`<section class="card"><span class="badge">AHORA LLEVEMOS ESTA ENSEÑANZA A LA VIDA</span><h1>${esc(current.tipo)} · ${esc(current.titulo)}</h1><p>Primero comprensión de la enseñanza; después discernimiento personal. Son dos momentos distintos.</p><div class="row"><button class="btn" onclick="showTest()">📝 Comprensión</button><button class="btn secondary" onclick="showDisc()">🔍 Discernimiento</button></div></section>`}
window.showTest=()=>{app.innerHTML=`<h1>📝 Comprensión de la enseñanza</h1><p class="muted">Las preguntas están construidas exclusivamente sobre esta sección del libro.</p>${current.test.map((q,i)=>`<div class="card question"><h3>${i+1}. ${esc(q.pregunta)}</h3>${q.opciones.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"> ${esc(o)}</label>`).join("")}</div>`).join("")}<button class="btn" onclick="grade()">Calificar comprensión</button><div id="result" class="section"></div>`}
window.grade=()=>{let ok=0,detail=[];current.test.forEach((q,i)=>{let x=document.querySelector(`input[name=q${i}]:checked`),good=x&&+x.value===q.correcta;if(good)ok++;detail.push(`<div class="feedback"><b>${i+1}. ${good?'✓ Correcta':'Revisar'}</b><br>${esc(q.explicacion)}</div>`)});let pct=Math.round(ok/current.test.length*100);state.test[current.id]=pct;save();$("#result").innerHTML=`<div class="card"><h2>Comprensión: ${pct}%</h2><p>${ok} de ${current.test.length} respuestas correctas.</p>${detail.join("")}<div class="row section"><button class="btn" onclick="showDisc()">Continuar a discernimiento →</button></div></div>`}
window.showDisc=()=>{app.innerHTML=`<h1>🔍 Discernimiento personal</h1><p class="muted">No hay respuestas correctas o incorrectas.</p>${current.discernimiento.map((q,i)=>`<div class="card question"><h3>${i+1}. ${esc(q.pregunta)}</h3>${q.opciones.map((o,j)=>`<label class="option"><input type="radio" name="d${i}" value="${j}"> ${esc(o)}</label>`).join("")}<div class="feedback">${esc(q.orientacion)}</div></div>`).join("")}<button class="btn" onclick="finishDisc()">Guardar mi discernimiento</button>`}
window.finishDisc=()=>{state.disc[current.id]=true;save();closing()}
function closing(){let prayer=current.secciones.find(s=>s.heading.startsWith("🙏"));let closing=current.secciones.find(s=>s.heading.startsWith("✨ FRASE"));let principle=current.secciones.find(s=>s.heading.startsWith("💬 PRINCIPIO"));app.innerHTML=`<section class="card reader"><h1>Cierre de la sección</h1>${principle?`<div class="head">${esc(principle.heading)}</div>${principle.lines.map(x=>`<p>${esc(x)}</p>`).join("")}`:""}${prayer?`<div class="head">${esc(prayer.heading)}</div>${prayer.lines.map(x=>`<p>${esc(x)}</p>`).join("")}`:""}${closing?`<div class="head">${esc(closing.heading)}</div><div class="quote">${closing.lines.map(esc).join("<br>")}</div>`:""}<button class="btn" onclick="finishSection()">✓ HE TERMINADO ESTA SECCIÓN</button></section>`}
window.finishSection=()=>{state.done[current.id]=true;save();let i=book.secciones.findIndex(s=>s.id===current.id),next=book.secciones[i+1];app.innerHTML=`<section class="card done"><h1>✓ ${esc(current.tipo)} completado</h1><h2>${esc(current.titulo)}</h2><p>📖 Enseñanza leída ✓<br>📝 Comprensión realizada ✓<br>🔍 Discernimiento realizado ✓<br>🙏 Cierre realizado ✓</p><div class="progress"><i style="width:${percent()}%"></i></div><p>${percent()}% del libro leído</p><div class="row">${next?`<button class="btn" onclick="openSection('${next.id}')">Continuar: ${esc(next.tipo)} →</button>`:"<button class='btn' onclick='finalResult()'>Ver resultado final →</button>"}<button class="btn secondary" onclick="openBook()">Índice</button><button class="btn secondary" onclick="journalForm('${book.id}','${current.id}')">📝 Registrar en mi cuaderno</button></div></section>`}
window.finalResult=()=>{let vals=Object.values(state.test),avg=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0;app.innerHTML=`<section class="card done"><h1>📚 ${esc(book.titulo)} completado</h1><h2>${esc(book.subtitulo)}</h2><p>Progreso de lectura: ${percent()}%</p><p>Promedio de comprensión: ${avg}%</p><p>Ha recorrido Prólogo, los 10 capítulos y la Conclusión usando el modelo maestro de lectura, comprensión y discernimiento.</p><div class="row"><button class="btn" onclick="openBook()">Volver al índice</button><button class="btn secondary" onclick="library()">Biblioteca</button></div></section>`}
function progress(){if(!book){app.innerHTML=`<section class="card"><h1>📊 Progreso de mi biblioteca</h1>${books.map(b=>`<div class="libraryProgress"><h2>${esc(b.titulo)}</h2><div class="progress"><i style="width:${bookPercent(b)}%"></i></div><p>${bookPercent(b)}% leído</p><button class="btn secondary" onclick="selectBook('${b.id}')">Ver libro</button></div>`).join("")}</section>`;return}app.innerHTML=`<section class="card"><h1>📊 Mi progreso · ${esc(book.titulo)}</h1><div class="progress"><i style="width:${percent()}%"></i></div><h2>${percent()}%</h2>${book.secciones.map(s=>`<p>${state.done[s.id]?'✓':'○'} ${esc(s.tipo)}: ${esc(s.titulo)} ${state.test[s.id]!=null?`— Comprensión ${state.test[s.id]}%`:""}</p>`).join("")}</section>`}
function cleanMarks(t){return (t||'').replace(/^[💬✨➡️📖]\s*/u,'').replace(/^“|”$/g,'').trim()}
function getPills(b,sectionId){
 let out=[];
 b.secciones.filter(s=>!sectionId||s.id===sectionId).forEach(s=>{
  s.secciones.forEach((g,gi)=>g.lines.forEach((line,li)=>{
   let t=(line||'').trim(); if(!(t.startsWith('💬')||t.startsWith('✨')))return;
   let ref=s.referencia||'', verse=s.versiculo||'';
   if(!ref && b.id==='hombre-altar'){ref='Hechos 9:10';verse='“Había entonces en Damasco un discípulo llamado Ananías, a quien el Señor dijo en visión: Ananías. Y él respondió: Heme aquí, Señor.”'}
   for(let k=li-1;k>=0;k--){let z=(g.lines[k]||'').trim();if(z.startsWith('📖')){ref=z.replace(/^📖\s*/,'').trim();let nv=(g.lines[k+1]||'').trim();if(nv && !nv.startsWith('💬')&&!nv.startsWith('✨'))verse=nv;break}}
   let exp=[];
   for(let k=li+1;k<g.lines.length && exp.length<4;k++){let z=(g.lines[k]||'').trim();if(!z||z.startsWith('💬')||z.startsWith('✨')||z.startsWith('📖'))break;exp.push(z)}
   if(!exp.length && gi+1<s.secciones.length){for(let z of s.secciones[gi+1].lines){z=(z||'').trim();if(!z||z.startsWith('💬')||z.startsWith('✨')||z.startsWith('📖'))break;exp.push(z);if(exp.length>=4)break}}
   if(!exp.length && gi>0){let prev=s.secciones[gi-1].lines.filter(z=>{z=(z||'').trim();return z&&!z.startsWith('💬')&&!z.startsWith('✨')&&!z.startsWith('📖')&&!z.startsWith('👉')});exp=prev.slice(-4)}
   out.push({bookId:b.id,book:b.titulo,sectionId:s.id,section:s.titulo,text:cleanMarks(t),type:'Píldora',reference:ref,verse:verse,explanation:exp.join(' ')});
  }));
 });return out
}
window.pills=(bookId,sectionId,idx=0)=>{
 let b=books.find(x=>x.id===bookId),ps=getPills(b,sectionId); idx=Math.max(0,Math.min(Number(idx)||0,Math.max(0,ps.length-1)));
 if(!ps.length){app.innerHTML=`<section class="card"><button class="btn secondary" onclick="selectBook('${b.id}')">← Libro</button><div class="feedback">Esta sección no contiene frases marcadas como píldoras.</div></section>`;return}
 let p=ps[idx], prev=idx>0?idx-1:ps.length-1, next=idx<ps.length-1?idx+1:0;
 app.innerHTML=`<section class="spiritualPill">
 <div class="pillTop"><button class="pillBack" onclick="${sectionId?`goToSection('${b.id}','${sectionId}')`:`selectBook('${b.id}')`}">‹ <span>Volver</span></button><div class="pillTitle">💡 <strong>PÍLDORA ESPIRITUAL</strong></div><div class="pillPager"><span>${idx+1} de ${ps.length}</span><button onclick="pills('${b.id}',${sectionId?`'${sectionId}'`:'null'},${prev})">‹</button><button onclick="pills('${b.id}',${sectionId?`'${sectionId}'`:'null'},${next})">›</button></div></div>
 <div class="pillBody"><div class="pillStatement">💬 <span>${esc(p.text)}</span></div>
 ${p.reference?`<div class="pillScripture"><div class="pillRef">📖 ${esc(p.reference)}</div><div class="pillVerse">${esc(p.verse||'')}</div></div>`:''}
 ${p.explanation?`<div class="pillExplanation"><span class="arrowBox">➡</span><span>${esc(p.explanation)}</span></div>`:''}
 <div class="pillSignature"><span></span><em>Constructores del Reino</em><span></span></div>
 <div class="pillActions"><button onclick='saveRaw(${JSON.stringify(p)})'>♡ <b>Guardar</b></button><button onclick='sharePill(${JSON.stringify(p)})'>⌯ <b>Compartir</b></button><button onclick='downloadCard(${JSON.stringify(p.text)},${JSON.stringify(p.book)},${JSON.stringify(p.section)},${JSON.stringify(p.reference||'')},${JSON.stringify(p.verse||'')})'>▧ <b>Crear imagen</b></button><button onclick='bookmarkPicker(${JSON.stringify(p)})'>🔖 <b>Crear separador</b></button><button onclick="goToSection('${p.bookId}','${p.sectionId}')">▤ <b>Ver en el libro</b></button></div>
 <div class="pillOrigin">${esc(p.book)} · ${esc(p.section)} · Leonard Moon</div></div></section>`;
}
window.goToSection=(bid,sid)=>{book=books.find(b=>b.id===bid);state=loadState(bid);openSection(sid)}
window.saveItem=(type,text,label)=>{if(!book||!current)return;saveRaw({type,text,bookId:book.id,book:book.titulo,sectionId:current.id,section:label||current.titulo})}
window.saveRaw=item=>{let c=loadCollection(),key=`${item.bookId}|${item.sectionId}|${item.type}|${item.text}`;if(!c.some(x=>x.key===key)){c.unshift({...item,key,date:new Date().toISOString()});saveCollection(c);alert('Guardado en Mi colección.')}else alert('Esta enseñanza ya está guardada.')}
window.collection=()=>{let c=loadCollection();app.innerHTML=`<section class="card"><span class="badge">❤️ MI COLECCIÓN</span><h1>Enseñanzas que he guardado</h1><input id="collectionSearch" class="searchBox" placeholder="Buscar en mi colección..." oninput="filterCollection()"><div id="collectionList">${renderCollection(c)}</div></section>`}
function renderCollection(c){return c.length?c.map((x,i)=>`<article class="saved"><span class="badge">${esc(x.type)}</span><h3>${esc(x.book)}</h3><p class="muted">${esc(x.section)}</p><blockquote>${esc(x.text)}</blockquote><div class="row"><button class="mini" onclick='shareText(${JSON.stringify(x.text)},${JSON.stringify(x.book)},${JSON.stringify(x.section)})'>📲 Compartir</button><button class="mini" onclick='downloadCard(${JSON.stringify(x.text)},${JSON.stringify(x.book)},${JSON.stringify(x.section)})'>🖼 Imagen</button><button class="mini danger" onclick="removeSaved('${x.key.replace(/'/g,"\\'")}')">Eliminar</button></div></article>`).join(''):'<p class="muted">Todavía no ha guardado enseñanzas.</p>'}
window.filterCollection=()=>{let q=$('#collectionSearch').value.toLowerCase(),c=loadCollection().filter(x=>`${x.text} ${x.book} ${x.section} ${x.type}`.toLowerCase().includes(q));$('#collectionList').innerHTML=renderCollection(c)}
window.removeSaved=key=>{saveCollection(loadCollection().filter(x=>x.key!==key));collection()}
function searchable(){let out=[];books.forEach(b=>b.secciones.forEach(s=>{let text=[s.titulo,s.subtitulo,s.referencia,s.versiculo,...s.secciones.flatMap(g=>[g.heading,...g.lines])].filter(Boolean).join(' ');out.push({b,s,text})}));return out}
window.searchLibrary=()=>{app.innerHTML=`<section class="card"><span class="badge">🔎 BUSCADOR DE TODA LA BIBLIOTECA</span><h1>¿Qué desea encontrar?</h1><p class="muted">Busca palabras y expresiones dentro del contenido de todos los libros.</p><input id="globalSearch" class="searchBox" placeholder="Ejemplo: altar, obediencia, congregados..." oninput="runSearch()"><div id="searchResults"></div></section>`;$('#globalSearch').focus()}
window.runSearch=()=>{let q=$('#globalSearch').value.trim().toLowerCase();if(q.length<2){$('#searchResults').innerHTML='';return}let r=searchable().filter(x=>x.text.toLowerCase().includes(q));$('#searchResults').innerHTML=`<p class="muted">${r.length} secciones encontradas.</p>`+r.map(x=>{let raw=x.text,idx=raw.toLowerCase().indexOf(q),snippet=raw.slice(Math.max(0,idx-90),idx+q.length+150);return `<article class="searchResult"><span class="badge">${esc(x.b.titulo)}</span><h3>${esc(x.s.tipo)} · ${esc(x.s.titulo)}</h3><p>…${esc(snippet)}…</p><button class="mini" onclick="goToSection('${x.b.id}','${x.s.id}')">📖 Abrir sección</button></article>`}).join('')}
window.shareText=(text,bookTitle,section)=>sharePill({text,book:bookTitle,section});
window.sharePill=p=>{let msg=`💡 PÍLDORA ESPIRITUAL\n\n“${p.text||''}”${p.reference?`\n\n📖 ${p.reference}\n${p.verse||''}`:''}${p.explanation?`\n\n➡️ ${p.explanation}`:''}\n\n${p.section||''}\n${p.book||''}\nLeonard Moon`;
 let wa='https://wa.me/?text='+encodeURIComponent(msg), mail='mailto:?subject='+encodeURIComponent('Píldora espiritual · '+(p.book||'Leonard Moon'))+'&body='+encodeURIComponent(msg);
 let old=document.getElementById('shareModal');if(old)old.remove();let m=document.createElement('div');m.id='shareModal';m.className='shareOverlay';m.innerHTML=`<div class="shareModal"><button class="shareClose" onclick="document.getElementById('shareModal').remove()">×</button><h2>📲 Compartir píldora</h2><p>Seleccione cómo desea compartirla.</p><a class="shareChoice whatsapp" href="${wa}" target="_blank" rel="noopener">WhatsApp</a><a class="shareChoice" href="${mail}">✉️ Correo electrónico</a><button class="shareChoice copy" id="copyPill">📋 Copiar texto</button></div>`;document.body.appendChild(m);document.getElementById('copyPill').onclick=async()=>{try{await navigator.clipboard.writeText(msg);alert('Píldora copiada.')}catch(e){let ta=document.createElement('textarea');ta.value=msg;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();alert('Píldora copiada.')}}}

function wrap(ctx,text,maxWidth){let words=text.split(/\s+/),lines=[],line='';for(let w of words){let t=line?line+' '+w:w;if(ctx.measureText(t).width>maxWidth&&line){lines.push(line);line=w}else line=t}if(line)lines.push(line);return lines}
window.downloadCard=(text,bookTitle,section,reference='',verse='')=>{let c=document.createElement('canvas');c.width=1080;c.height=1350;let x=c.getContext('2d');let bg=x.createLinearGradient(0,0,1080,1350);bg.addColorStop(0,'#ffffff');bg.addColorStop(1,'#f3efff');x.fillStyle=bg;x.fillRect(0,0,c.width,c.height);x.fillStyle='#6f48ff';x.fillRect(0,0,18,1350);x.textAlign='center';x.fillStyle='#32216f';x.font='700 42px Georgia';x.fillText('💡  PÍLDORA ESPIRITUAL',540,115);x.strokeStyle='#ded5ff';x.lineWidth=3;x.beginPath();x.moveTo(90,155);x.lineTo(990,155);x.stroke();x.fillStyle='#4022c9';x.font='italic 50px Georgia';let q=wrap(x,'“'+text+'”',850),y=255;q.slice(0,8).forEach(l=>{x.fillText(l,540,y);y+=67});if(reference){y+=25;x.fillStyle='#29253a';x.font='700 34px Georgia';x.fillText('📖  '+reference,540,y);if(verse){y+=55;x.font='30px Georgia';let vl=wrap(x,'“'+verse+'”',820);vl.slice(0,3).forEach(l=>{x.fillText(l,540,y);y+=43})}}let boxY=Math.max(y+55,760);x.fillStyle='#eee9ff';roundRect(x,75,boxY,930,235,28);x.fill();x.fillStyle='#51456f';x.font='28px Georgia';let msg='Una enseñanza para volver al libro, meditar la Palabra y permitir que Cristo forme nuestra manera de vivir.';let ml=wrap(x,msg,820),my=boxY+70;ml.forEach(l=>{x.fillText(l,540,my);my+=42});x.fillStyle='#7657e8';x.font='28px Georgia';x.fillText('—  Constructores del Reino  —',540,boxY+205);x.fillStyle='#3d3264';x.font='700 28px Georgia';let sl=wrap(x,section.toUpperCase(),900).slice(0,3),sy=1115;sl.forEach(l=>{x.fillText(l,540,sy);sy+=38});sy+=12;x.font='30px Georgia';x.fillText(bookTitle.toUpperCase(),540,sy);sy+=48;x.font='italic 29px Georgia';x.fillText('Leonard Moon',540,sy);let a=document.createElement('a');a.download='pildora-espiritual-leonard-moon.png';a.href=c.toDataURL('image/png');a.click()} 

const bookmarkThemes=[
 {name:'Camino',tag:'La Palabra como guía',a:'#f6e5bd',b:'#7a4a20',accent:'#9a642c',scene:'path'},
 {name:'Fortaleza',tag:'Cristo me sostiene',a:'#d8efff',b:'#123e70',accent:'#1b5d9c',scene:'mountain'},
 {name:'Esperanza',tag:'Su fidelidad permanece',a:'#ffe0d5',b:'#8b2520',accent:'#c54a3e',scene:'sun'},
 {name:'Fruto',tag:'Vida que permanece',a:'#e3f3d5',b:'#285d1c',accent:'#4d862d',scene:'leaves'},
 {name:'Refugio',tag:'Seguros en Su presencia',a:'#fff0b9',b:'#6d431b',accent:'#b67b1d',scene:'light'},
 {name:'Propósito',tag:'La verdad llevada a la vida',a:'#dceeff',b:'#173e75',accent:'#2367b4',scene:'steps'}
];
window.bookmarkPicker=p=>{let old=document.getElementById('bookmarkModal');if(old)old.remove();let m=document.createElement('div');m.id='bookmarkModal';m.className='shareOverlay bookmarkOverlay';m.innerHTML=`<div class="bookmarkModal"><button class="shareClose" onclick="document.getElementById('bookmarkModal').remove()">×</button><span class="badge">🔖 SEPARADORES DE PÍLDORAS</span><h2>Elija un diseño para esta píldora</h2><p>Los seis modelos conservan exactamente la misma píldora, Palabra y procedencia del libro.</p><div class="bookmarkChoices">${bookmarkThemes.map((t,i)=>`<button onclick='downloadBookmark(${JSON.stringify(p)},${i})'><span class="bookmarkSwatch" style="--ba:${t.a};--bb:${t.b};--bc:${t.accent}"><i>▱</i><strong>${i+1}</strong></span><b>${t.name}</b><small>${t.tag}</small></button>`).join('')}</div><div class="bookmarkNote">Después de generarlo podrá guardarlo o compartir la imagen desde su dispositivo.</div></div>`;document.body.appendChild(m)};
function bookmarkScene(ctx,t){let g=ctx.createLinearGradient(0,450,0,1600);g.addColorStop(0,t.a);g.addColorStop(1,t.b);ctx.fillStyle=g;ctx.fillRect(0,0,650,1800);ctx.globalAlpha=.18;ctx.fillStyle=t.accent;for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(80+i*90,1200+(i%3)*80,170,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle='rgba(255,255,255,.18)';ctx.beginPath();ctx.moveTo(0,1420);ctx.lineTo(250,1120);ctx.lineTo(390,1280);ctx.lineTo(650,1010);ctx.lineTo(650,1800);ctx.lineTo(0,1800);ctx.closePath();ctx.fill()}
function fitLines(ctx,text,maxWidth,maxLines,startSize,minSize=27){for(let size=startSize;size>=minSize;size-=2){ctx.font=`italic 700 ${size}px Georgia`;let ls=wrap(ctx,text,maxWidth);if(ls.length<=maxLines)return {size,lines:ls}}ctx.font=`italic 700 ${minSize}px Georgia`;let ls=wrap(ctx,text,maxWidth).slice(0,maxLines);if(ls.length){let last=ls.length-1;while(ctx.measureText(ls[last]+'…').width>maxWidth&&ls[last].length>3)ls[last]=ls[last].slice(0,-2);ls[last]+='…'}return {size:minSize,lines:ls}}
window.downloadBookmark=(p,themeIndex=0)=>{let t=bookmarkThemes[themeIndex]||bookmarkThemes[0],c=document.createElement('canvas');c.width=650;c.height=1800;let x=c.getContext('2d');bookmarkScene(x,t);x.fillStyle='rgba(255,255,255,.91)';roundRect(x,28,28,594,1744,65);x.fill();x.save();roundRect(x,28,28,594,1744,65);x.clip();let bg=x.createLinearGradient(0,0,0,1800);bg.addColorStop(0,t.a);bg.addColorStop(.62,'rgba(255,255,255,.92)');bg.addColorStop(1,t.b);x.fillStyle=bg;x.globalAlpha=.92;x.fillRect(28,28,594,1744);x.globalAlpha=1;x.restore();x.fillStyle=t.accent;roundRect(x,210,25,230,210,0);x.fill();x.fillStyle='#fff';x.textAlign='center';x.font='54px Georgia';x.fillText('✦',325,112);x.font='700 25px Georgia';x.fillText('PÍLDORA',325,164);x.fillStyle='#25231f';let f=fitLines(x,'“'+(p.text||'')+'”',500,8,48,32),y=300;x.font=`italic 700 ${f.size}px Georgia`;for(let l of f.lines){x.fillText(l,325,y);y+=f.size*1.25}if(p.reference){y+=25;x.fillStyle=t.accent;x.font='700 29px Georgia';x.fillText('📖  '+p.reference,325,y);if(p.verse){y+=45;x.fillStyle='#34302a';x.font='25px Georgia';let vs=wrap(x,'“'+p.verse.replace(/[“”"]/g,'')+'”',500).slice(0,5);for(let l of vs){x.fillText(l,325,y);y+=34}}}x.fillStyle='rgba(255,255,255,.78)';roundRect(x,75,Math.max(y+35,1000),500,190,28);x.fill();let ay=Math.max(y+80,1050);x.fillStyle=t.b;x.font='700 24px Georgia';x.fillText('PARA VOLVER A LA PALABRA',325,ay);x.font='23px Georgia';x.fillStyle='#45413a';let al=wrap(x,'Lee, comprende, enseña y vive.',430);for(let l of al){ay+=34;x.fillText(l,325,ay)}x.fillStyle='#fff';x.font='700 29px Georgia';let sy=1475,sl=wrap(x,(p.section||'').toUpperCase(),510).slice(0,3);for(let l of sl){x.fillText(l,325,sy);sy+=36}sy+=20;x.strokeStyle='rgba(255,255,255,.65)';x.lineWidth=2;x.beginPath();x.moveTo(205,sy);x.lineTo(445,sy);x.stroke();sy+=32;x.font='700 17px Arial';x.fillText('LIBRO',325,sy);sy+=38;x.font='700 35px Georgia';let bl=wrap(x,(p.book||'').toUpperCase(),500).slice(0,2);for(let l of bl){x.fillText(l,325,sy);sy+=40}sy+=10;x.font='italic 28px Georgia';x.fillText('Leonard Moon',325,sy);sy+=42;x.font='19px Arial';x.fillText('BIBLIOTECA DIGITAL · Una biblioteca para vivir la Palabra',325,sy);c.toBlob(blob=>{if(!blob)return alert('No fue posible generar el separador.');showBookmarkPreview(blob,p,t)},'image/png')};
window.showBookmarkPreview=(blob,p,t)=>{document.getElementById('bookmarkModal')?.remove();document.getElementById('bookmarkPreviewModal')?.remove();let url=URL.createObjectURL(blob),filename=`separador-${(p.book||'libro').toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${t.name.toLowerCase()}.png`;window._bookmarkPreview={blob,url,filename};let m=document.createElement('div');m.id='bookmarkPreviewModal';m.className='shareOverlay bookmarkPreviewOverlay';m.innerHTML=`<div class="bookmarkPreviewModal"><button class="shareClose" onclick="closeBookmarkPreview()">×</button><span class="badge">🔖 SEPARADOR LISTO</span><h2>Visualice primero su separador</h2><div class="bookmarkPreviewImage"><img src="${url}" alt="Separador generado"></div><div class="bookmarkPreviewActions"><button class="btn" onclick="shareBookmarkNative()">↗ Compartir / Guardar</button><button class="btn secondary" onclick="saveBookmarkFile()">⇩ Guardar archivo</button></div><p class="bookmarkIOSHelp">En iPhone y iPad use <b>Compartir / Guardar</b> para abrir la hoja de Apple. Desde allí puede elegir <b>Guardar imagen</b> o <b>Guardar en Archivos</b>.</p></div>`;document.body.appendChild(m)};
window.closeBookmarkPreview=()=>{let d=window._bookmarkPreview;if(d?.url)URL.revokeObjectURL(d.url);window._bookmarkPreview=null;document.getElementById('bookmarkPreviewModal')?.remove()};
window.shareBookmarkNative=async()=>{let d=window._bookmarkPreview;if(!d)return;let file=new File([d.blob],d.filename,{type:'image/png'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file],title:'Separador · Biblioteca Digital'});return}}catch(e){if(e?.name==='AbortError')return}saveBookmarkFile()};
window.saveBookmarkFile=()=>{let d=window._bookmarkPreview;if(!d)return;let a=document.createElement('a');a.href=d.url;a.download=d.filename;document.body.appendChild(a);a.click();a.remove()};
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
window.formation=()=>{let j=loadJournal(),c=loadCollection();app.innerHTML=`<section class="formationHero"><span class="badge">🌿 MI CAMINO DE FORMACIÓN</span><h1>Lo que estoy aprendiendo a través de mis libros</h1><p class="muted">Un espacio para ver mi recorrido, conservar lo que he recibido y registrar decisiones personales.</p></section><section class="formationGrid"><article class="formationCard"><div class="formationIcon">📚</div><h2>Mi recorrido</h2>${books.map(b=>{let st=loadState(b.id),last=st.last?sectionLabel(b,st.last):'Aún no iniciado';return `<div class="routeBook"><b>${esc(b.titulo)}</b><div class="progress"><i style="width:${bookPercent(b)}%"></i></div><small>${bookPercent(b)}% · ${esc(last)}</small></div>`}).join('')}<button class="btn secondary" onclick="progress()">Ver progreso completo</button></article><article class="formationCard"><div class="formationIcon">📝</div><h2>Mi cuaderno</h2><p>${j.length} registro${j.length===1?'':'s'} personal${j.length===1?'':'es'}.</p><p class="muted">Lo que me habló, lo que debo revisar y la decisión que quiero tomar.</p><button class="btn" onclick="journal()">Abrir mi cuaderno</button></article><article class="formationCard"><div class="formationIcon">❤️</div><h2>Lo que he guardado</h2><p>${c.length} enseñanza${c.length===1?'':'s'} en Mi colección.</p><p class="muted">Píldoras, frases y porciones bíblicas que quiero conservar.</p><button class="btn secondary" onclick="collection()">Abrir Mi colección</button></article><article class="formationCard"><div class="formationIcon">🌱</div><h2>Lo que estoy trabajando</h2><p>${j.filter(x=>x.revisar||x.decision).length} registro${j.filter(x=>x.revisar||x.decision).length===1?'':'s'} con revisión o decisión.</p><p class="muted">Aquí aparecen únicamente asuntos que yo mismo he escrito; la aplicación no interpreta ni atribuye mensajes espirituales.</p><button class="btn secondary" onclick="workingOn()">Ver mis decisiones</button></article></section><section class="card section"><div class="row"><button class="btn" onclick="historyFormation()">📜 Mi historia de formación</button><button class="btn secondary" onclick="library()">← Biblioteca</button></div></section>`}
window.journalForm=(bid,sid)=>{let b=books.find(x=>x.id===bid),sec=b.secciones.find(x=>x.id===sid),old=loadJournal().find(x=>x.bookId===bid&&x.sectionId===sid);app.innerHTML=`<section class="card journalForm"><span class="badge">📝 MI CUADERNO</span><h1>${esc(b.titulo)}</h1><h2>${esc(sec.tipo)} · ${esc(sec.titulo)}</h2><label>¿Qué me habló de manera especial?</label><textarea id="jHablo" placeholder="Escriba con sus propias palabras...">${esc(old?.hablo||'')}</textarea><label>¿Qué debo revisar en mi vida?</label><textarea id="jRevisar" placeholder="Escriba lo que desea revisar...">${esc(old?.revisar||'')}</textarea><label>¿Qué decisión quiero tomar?</label><textarea id="jDecision" placeholder="Escriba una decisión concreta...">${esc(old?.decision||'')}</textarea><div class="row"><button class="btn" onclick="saveJournalEntry('${bid}','${sid}')">Guardar en mi cuaderno</button><button class="btn secondary" onclick="goToSection('${bid}','${sid}')">Volver al capítulo</button></div></section>`}
window.saveJournalEntry=(bid,sid)=>{let b=books.find(x=>x.id===bid),sec=b.secciones.find(x=>x.id===sid),j=loadJournal(),entry={bookId:bid,book:b.titulo,sectionId:sid,section:`${sec.tipo} · ${sec.titulo}`,hablo:$('#jHablo').value.trim(),revisar:$('#jRevisar').value.trim(),decision:$('#jDecision').value.trim(),date:new Date().toISOString()};j=j.filter(x=>!(x.bookId===bid&&x.sectionId===sid));j.unshift(entry);saveJournal(j);alert('Registro guardado en Mi cuaderno.');journal()}
window.journal=()=>{let j=loadJournal();app.innerHTML=`<section class="card"><span class="badge">📝 MI CUADERNO</span><h1>Mis registros de lectura</h1><p class="muted">Organizados por libro, sección y fecha.</p>${j.length?j.map((x,i)=>`<article class="journalEntry"><div class="journalDate">${new Date(x.date).toLocaleDateString('es-CO',{year:'numeric',month:'long',day:'numeric'})}</div><h2>${esc(x.book)}</h2><h3>${esc(x.section)}</h3>${x.hablo?`<h4>💡 Lo que me habló</h4><p>${esc(x.hablo)}</p>`:''}${x.revisar?`<h4>🔍 Lo que debo revisar</h4><p>${esc(x.revisar)}</p>`:''}${x.decision?`<h4>🎯 Mi decisión</h4><p>${esc(x.decision)}</p>`:''}<div class="row"><button class="mini" onclick="journalForm('${x.bookId}','${x.sectionId}')">Editar</button><button class="mini" onclick="goToSection('${x.bookId}','${x.sectionId}')">Ver capítulo</button><button class="mini danger" onclick="deleteJournal(${i})">Eliminar</button></div></article>`).join(''):'<div class="feedback">Todavía no ha escrito en su cuaderno. Al terminar una sección use “Registrar en mi cuaderno”.</div>'}<div class="row section"><button class="btn secondary" onclick="formation()">← Mi camino de formación</button></div></section>`}
window.deleteJournal=i=>{let j=loadJournal();j.splice(i,1);saveJournal(j);journal()}
window.workingOn=()=>{let j=loadJournal().filter(x=>x.revisar||x.decision);app.innerHTML=`<section class="card"><span class="badge">🌱 LO QUE ESTOY TRABAJANDO</span><h1>Revisiones y decisiones que yo mismo he registrado</h1><p class="muted">Este espacio no interpreta sus respuestas. Solamente organiza lo que usted escribió durante su lectura.</p>${j.length?j.map(x=>`<article class="workItem"><h3>${esc(x.book)} · ${esc(x.section)}</h3>${x.revisar?`<p><b>🔍 Revisar:</b> ${esc(x.revisar)}</p>`:''}${x.decision?`<p><b>🎯 Decisión:</b> ${esc(x.decision)}</p>`:''}</article>`).join(''):'<div class="feedback">Aún no hay revisiones o decisiones registradas.</div>'}<button class="btn secondary" onclick="formation()">← Mi camino de formación</button></section>`}
window.historyFormation=()=>{let j=loadJournal();app.innerHTML=`<section class="card"><span class="badge">📜 MI HISTORIA DE FORMACIÓN</span><h1>Mi recorrido personal</h1><p class="muted">Una línea de tiempo construida únicamente con mis propios registros.</p><div class="timeline">${j.length?j.map(x=>`<article class="timelineItem"><div class="timelineDot"></div><div><div class="journalDate">${new Date(x.date).toLocaleDateString('es-CO',{year:'numeric',month:'long',day:'numeric'})}</div><h3>${esc(x.book)}</h3><p>${esc(x.section)}</p>${x.decision?`<p><b>Decisión registrada:</b> ${esc(x.decision)}</p>`:''}</div></article>`).join(''):'<div class="feedback">Su historia comenzará cuando guarde el primer registro en Mi cuaderno.</div>'}</div><button class="btn secondary" onclick="formation()">← Mi camino de formación</button></section>`}
document.querySelector("#homeBtn").onclick=ministryHome;document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{let n=b.dataset.nav;if(n==='inicio')ministryHome();else if(n==='biblioteca')library();else if(n==='progreso')progress();else if(n==='buscar')searchLibrary();else if(n==='formacion')formation();else collection()});

// v1.6 · Perfil y respaldo local
const profileKey='bd_perfil_v16';
function loadProfile(){try{return JSON.parse(localStorage.getItem(profileKey)||'{}')}catch{return {}}}
function saveProfileData(p){localStorage.setItem(profileKey,JSON.stringify(p||{}))}
function profileName(){return (loadProfile().name||'').trim()}
function downloadJSON(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
window.profileBackup=()=>{const p=loadProfile();app.innerHTML=`<section class="card profileCard"><span class="badge">🔐 MI PERFIL Y RESPALDO</span><h1>Mi espacio personal</h1><p class="muted">Estos datos se guardan únicamente en este navegador. No se mezclan con los de otros lectores que usen la misma dirección de GitHub Pages.</p><label>¿Cómo quieres que te llamemos?</label><input id="profileName" class="profileInput" maxlength="60" value="${esc(p.name||'')}" placeholder="Tu nombre"><div class="row"><button class="btn" onclick="saveProfileName()">Guardar nombre</button></div><hr><h2>Respaldo de mi recorrido</h2><p>Guarda en un archivo tu progreso, cuaderno, colección y datos de formación para poder recuperarlos en otro navegador o dispositivo.</p><div class="row"><button class="btn" onclick="exportJourney()">📤 Exportar mi recorrido</button><label class="btn secondary importBtn">📥 Recuperar mi recorrido<input id="importJourney" type="file" accept="application/json,.json" hidden onchange="importJourneyFile(this.files[0])"></label></div><div class="feedback section"><b>Importante:</b> el archivo de respaldo contiene información personal que tú mismo hayas escrito en Mi Cuaderno. Guárdalo donde consideres seguro.</div><hr><h2>Comenzar de nuevo</h2><p class="muted">Borra únicamente los datos personales de esta Biblioteca en este navegador. Los libros y la aplicación no se eliminan.</p><button class="btn dangerBtn" onclick="resetJourney()">🗑️ Comenzar de nuevo</button><div class="row section"><button class="btn secondary" onclick="library()">← Biblioteca</button></div></section>`}
window.saveProfileName=()=>{const name=$('#profileName').value.trim();saveProfileData({name});alert(name?'Nombre guardado.':'Nombre eliminado.');library()}
window.exportJourney=()=>{const data={format:'biblioteca-digital-leonard-moon',version:1,exportedAt:new Date().toISOString(),data:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('bd_'))data.data[k]=localStorage.getItem(k)};const who=profileName().toLowerCase().replace(/[^a-z0-9áéíóúñ]+/gi,'-').replace(/^-|-$/g,'')||'lector';downloadJSON(data,`biblioteca-digital-respaldo-${who}.json`)}
window.importJourneyFile=async file=>{if(!file)return;try{const raw=await file.text(),obj=JSON.parse(raw);if(obj.format!=='biblioteca-digital-leonard-moon'||!obj.data||typeof obj.data!=='object')throw new Error('Formato no reconocido');if(!confirm('Este respaldo reemplazará los datos actuales de esta Biblioteca en este navegador. ¿Deseas continuar?'))return;Object.keys(localStorage).filter(k=>k.startsWith('bd_')).forEach(k=>localStorage.removeItem(k));Object.entries(obj.data).forEach(([k,v])=>{if(k.startsWith('bd_')&&typeof v==='string')localStorage.setItem(k,v)});alert('Recorrido recuperado correctamente.');library()}catch(e){alert('No fue posible recuperar este archivo. Verifica que sea un respaldo creado por Biblioteca Digital.')}}
window.resetJourney=()=>{if(!confirm('¿Seguro que deseas comenzar de nuevo? Se borrarán progreso, cuaderno, colección y perfil guardados en este navegador.'))return;if(!confirm('Esta acción no se puede deshacer salvo que tengas un respaldo exportado. ¿Continuar?'))return;Object.keys(localStorage).filter(k=>k.startsWith('bd_')).forEach(k=>localStorage.removeItem(k));book=null;current=null;state=null;alert('Tu recorrido local fue reiniciado.');library()}
function welcomeIfNeeded(){if(localStorage.getItem('bd_welcome_v16'))return;localStorage.setItem('bd_welcome_v16','1');setTimeout(()=>{let old=document.getElementById('welcomeModal');if(old)return;let m=document.createElement('div');m.id='welcomeModal';m.className='shareOverlay';m.innerHTML=`<div class="shareModal welcomeModal"><button class="shareClose" onclick="document.getElementById('welcomeModal').remove()">×</button><h2>📚 Bienvenido a Biblioteca Digital</h2><p>Tu recorrido se guardará solamente en este navegador.</p><input id="welcomeName" class="profileInput" maxlength="60" placeholder="¿Cómo quieres que te llamemos?"><div class="row"><button class="btn" onclick="saveWelcomeName()">Comenzar mi recorrido</button><button class="btn secondary" onclick="document.getElementById('welcomeModal').remove()">Ahora no</button></div></div>`;document.body.appendChild(m)},200)}
window.saveWelcomeName=()=>{let n=document.getElementById('welcomeName').value.trim();if(n)saveProfileData({name:n});document.getElementById('welcomeModal')?.remove();library()}
// Corrige navegación inferior de Formación y añade acceso al perfil.
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{let n=b.dataset.nav;if(n==='biblioteca')library();else if(n==='progreso')progress();else if(n==='buscar')searchLibrary();else if(n==='formacion')formation();else collection()});
setTimeout(welcomeIfNeeded,350);


// v1.9 · MOTOR DE ENSEÑANZAS EXTRAÍDAS DE LOS LIBROS
// No crea doctrina nueva: cada enseñanza se construye únicamente con bloques ya escritos en biblioteca.json.
const teachSkip=/INTRODUCCIÓN|PREGUNTAS DE DISCERNIMIENTO|ORACIÓN FINAL|CITA CLAVE|PRINCIPIO FINAL|FRASE DE CIERRE/i;
function cleanHeading(h){return (h||'').replace(/^[^A-Za-zÁÉÍÓÚÜÑ0-9¿¡]+/,'').trim()}
function cleanTeachingLine(t){return (t||'').replace(/^[💬✨🔥🌿🌊➡👉]+\s*/u,'').trim()}
function teachingCatalog(){let out=[];books.forEach(b=>b.secciones.forEach(sec=>sec.secciones.forEach((g,gi)=>{let title=cleanHeading(g.heading);if(!title||teachSkip.test(title))return;let lines=(g.lines||[]).map(x=>(x||'').trim()).filter(Boolean);let prose=lines.filter(x=>!x.startsWith('📖')&&!x.startsWith('💬')&&!x.startsWith('✨')).map(cleanTeachingLine).filter(Boolean);if(prose.length<2)return;let ref=sec.referencia||'',verse=sec.versiculo||'';for(let i=0;i<lines.length;i++){if(lines[i].startsWith('📖')){ref=lines[i].replace(/^📖\s*/,'').trim();let n=(lines[i+1]||'').trim();if(n&&!n.startsWith('💬')&&!n.startsWith('✨')&&!n.startsWith('📖'))verse=n;break}}
let q=lines.find(x=>x.startsWith('💬')||x.startsWith('✨'));q=q?cleanMarks(q):'';
out.push({id:`${b.id}|${sec.id}|${gi}`,bookId:b.id,book:b.titulo,sectionId:sec.id,section:`${sec.tipo} · ${sec.titulo}`,title,reference:ref,verse,paragraphs:prose,pill:q,category:(b.categoria||'Biblioteca').split('·')[0].trim()||'Biblioteca'});})));return out}
let teachingFilter='todos';
window.teachings=()=>{let cats=['todos',...new Set(books.map(b=>b.titulo))];app.innerHTML=`<section class="teachHero"><span class="badge">📖 ENSEÑANZAS DEL MINISTERIO</span><h1>Verdades extraídas de nuestra Biblioteca</h1><p>El libro es la fuente. Cada enseñanza que aparece aquí nace del contenido real escrito por Leonard Moon y conduce nuevamente al libro de origen.</p></section><section class="teachToolbar"><input id="teachSearch" placeholder="Buscar una enseñanza, tema o texto bíblico..." oninput="renderTeachings()">${cats.map((c,i)=>`<button class="teachFilter ${i===0?'active':''}" data-tf="${esc(c)}" onclick="setTeachingFilter(this,${JSON.stringify(c)})">${i===0?'Todas':esc(c)}</button>`).join('')}</section><div id="teachResults"></div>`;teachingFilter='todos';renderTeachings()}
window.setTeachingFilter=(el,val)=>{teachingFilter=val;document.querySelectorAll('.teachFilter').forEach(x=>x.classList.remove('active'));el.classList.add('active');renderTeachings()}
window.renderTeachings=()=>{let q=(document.getElementById('teachSearch')?.value||'').trim().toLowerCase(),all=teachingCatalog(),r=all.filter(t=>(teachingFilter==='todos'||t.book===teachingFilter)&&(!q||`${t.title} ${t.book} ${t.section} ${t.reference} ${t.paragraphs.join(' ')}`.toLowerCase().includes(q)));let host=document.getElementById('teachResults');if(!host)return;host.innerHTML=`<div class="teachCount">${r.length} enseñanza${r.length===1?'':'s'} extraída${r.length===1?'':'s'} de ${books.length} libro${books.length===1?'':'s'}.</div>`+(r.length?`<section class="teachGrid">${r.map(t=>`<article class="teachCard"><div class="source">EXTRAÍDA DE ${esc(t.book)}</div><h2>${esc(t.title)}</h2>${t.reference?`<div class="ref">📖 ${esc(t.reference)}</div>`:''}<p>${esc(t.paragraphs.slice(0,3).join(' '))}</p><button class="btn" onclick='openTeaching(${JSON.stringify(t.id)})'>Leer enseñanza →</button></article>`).join('')}</section>`:`<div class="teachEmpty">No encontramos enseñanzas con esa búsqueda.</div>`)}
window.openTeaching=id=>{let t=teachingCatalog().find(x=>x.id===id);if(!t)return teachings();let p=t.pill||t.paragraphs[0]||'';let pillObj={bookId:t.bookId,book:t.book,sectionId:t.sectionId,section:t.section,text:p,type:'Enseñanza',reference:t.reference,verse:t.verse,explanation:t.paragraphs.slice(0,3).join(' ')};app.innerHTML=`<article class="teachingDetail"><div class="teachingHead"><button class="btn secondary" onclick="teachings()">← Enseñanzas</button><div class="source">ENSEÑANZA EXTRAÍDA DE ${esc(t.book)}</div><h1>${esc(t.title)}</h1><p>${esc(t.section)}</p></div><div class="teachingBody">${t.reference?`<div class="teachScripture"><b>📖 ${esc(t.reference)}</b><div>${esc(t.verse||'')}</div></div>`:''}<section class="teachBlock"><h2>Contenido de la enseñanza</h2>${t.paragraphs.map(x=>`<p>${esc(x)}</p>`).join('')}</section>${t.pill?`<section class="teachPill"><b>💡 Píldora destacada</b><blockquote>“${esc(t.pill)}”</blockquote></section>`:''}<div class="teachActions"><button class="btn" onclick='sharePill(${JSON.stringify(pillObj)})'>📲 Compartir</button><button class="btn secondary" onclick='saveRaw(${JSON.stringify(pillObj)})'>♡ Guardar</button><button class="btn secondary" onclick='bookmarkPicker(${JSON.stringify(pillObj)})'>🔖 Crear separador</button><button class="btn secondary" onclick="goToSection('${t.bookId}','${t.sectionId}')">📚 Ir al libro completo</button></div><div class="teachOrigin"><b>Fuente:</b> ${esc(t.book)} · ${esc(t.section)} · Leonard Moon<br><small>Esta enseñanza se presenta a partir del contenido existente del libro; no añade una doctrina independiente al texto de origen.</small></div></div></article>`}

// v2.0 · VIDEOTECA DEL MINISTERIO

let ministryResources=[];
let publicResources=[];
let resourceFilter='todos';
const RESOURCE_STORE_KEY='ministerio_recursos_local_v21';
function loadLocalResources(){try{return JSON.parse(localStorage.getItem(RESOURCE_STORE_KEY)||'[]')}catch(e){return []}}
function saveLocalResources(){localStorage.setItem(RESOURCE_STORE_KEY,JSON.stringify(ministryResources))}
function resourceCats(){return ['todos',...new Set(ministryResources.map(r=>r.categoria).filter(Boolean))]}
window.setResourceFilter=(el,c)=>{resourceFilter=c;document.querySelectorAll('.resourceFilter').forEach(x=>x.classList.remove('active'));el.classList.add('active');renderResources();enforceVisitorPermissions()}
window.renderResources=()=>{let filters=document.getElementById('resourceFilters');if(filters)filters.innerHTML=resourceCats().map(c=>`<button class="resourceFilter ${resourceFilter===c?'active':''}" onclick="setResourceFilter(this,'${String(c).replace(/'/g,"\\'")}')">${c==='todos'?'Todos':esc(c)}</button>`).join('');let q=(document.getElementById('resourceSearch')?.value||'').trim().toLowerCase();let rows=ministryResources.filter(r=>(resourceFilter==='todos'||r.categoria===resourceFilter)&&(!q||`${r.titulo||''} ${r.descripcion||''} ${r.libro||''}`.toLowerCase().includes(q)));let host=document.getElementById('resourceResults');if(!host)return;if(!ministryResources.length){host.innerHTML=`<section class="resourceEmpty"><div class="resourceEmptyIcon">📄</div><h2>La Biblioteca de Recursos está lista</h2><p>Aquí puede incorporar los PDF que quiera poner a disposición de quienes visiten el Ministerio.</p><button class="btn" onclick="openResourceUploader()">＋ Agregar mi primer recurso</button></section>`;return}let featured=rows.find(r=>r.destacado)||rows[0],rest=rows.filter(r=>!featured||r.id!==featured.id);host.innerHTML=`${featured?`<section class="resourceFeatured"><h2>☆ Recurso destacado</h2><article><div class="resourceCover">📄<b>PDF</b></div><div class="resourceInfo"><span class="resourceTag">${esc(featured.categoria||'Recurso')}</span><h3>${esc(featured.titulo)}</h3>${featured.libro?`<small>Relacionado con: ${esc(featured.libro)}</small>`:''}<p>${esc(featured.descripcion||'')}</p><div class="resourceMeta">${featured.fecha?`📅 ${esc(featured.fecha)}`:''}${featured.tamano?` <span>·</span> 📄 ${esc(featured.tamano)}`:''}</div></div><div class="resourceActions"><button class="btn" onclick="viewResource('${featured.id}')">👁 Ver en línea</button><button class="btn secondary" onclick="downloadResource('${featured.id}')">⇩ Descargar</button>${isAdminMode()?`<button class="btn danger" onclick="deleteResource('${featured.id}')">🗑 Eliminar</button>`:''}</div></article></section>`:''}<section class="resourceList"><div class="resourceListHead"><h2>▣ Más recursos</h2><span>${rows.length} recurso${rows.length===1?'':'s'}</span></div><div class="resourceGrid">${rest.map(r=>`<article class="resourceCard"><div class="resourceCardTop"><span>📄</span><b>PDF</b></div><span class="resourceTag">${esc(r.categoria||'Recurso')}</span><h3>${esc(r.titulo)}</h3>${r.libro?`<small>Relacionado con:<br>${esc(r.libro)}</small>`:''}<p>${esc(r.descripcion||'')}</p><div class="resourceCardActions"><button class="btn secondary" onclick="viewResource('${r.id}')">👁 Ver</button><button class="btn secondary" onclick="downloadResource('${r.id}')">⇩ Descargar</button>${isAdminMode()?`<button class="resourceDelete" onclick="deleteResource('${r.id}')" title="Eliminar">🗑</button>`:''}</div></article>`).join('')}</div></section>`}
window.openResourceUploader=()=>{if(!isAdminMode()){alert('Esta función está disponible únicamente en modo administrador.');return}app.innerHTML=`<section class="resourceUploadPage"><button class="btn secondary" onclick="resourcesPage()">← Volver a Recursos</button><div class="resourceUploadCard"><span class="badge">📄 NUEVO RECURSO</span><h1>Agregar recurso PDF</h1><p>Seleccione el material terminado y complete sus datos.</p><label>Archivo PDF<input id="ruFile" type="file" accept="application/pdf,.pdf"></label><label>Título<input id="ruTitle" placeholder="Título del recurso"></label><div class="resourceFormGrid"><label>Categoría<select id="ruCat"><option>Guía</option><option>Estudio</option><option>Familia</option><option>Finanzas</option><option>Formación</option><option>Plantilla</option><option>Otro</option></select></label><label>Libro relacionado (opcional)<input id="ruBook" placeholder="Ej. CONGREGADOS"></label></div><label>Descripción<textarea id="ruDesc" rows="4"></textarea></label><div class="resourceFormGrid"><label>Fecha<input id="ruDate" type="date"></label><label class="checkLine"><input id="ruFeatured" type="checkbox"> Marcar como recurso destacado</label></div><div class="resourceUploadNotice"><b>Prueba local:</b> el PDF queda guardado en este navegador/equipo. Para la publicación definitiva podremos alojar los materiales públicamente sin cargar innecesariamente la aplicación.</div><button class="btn" onclick="saveUploadedResource()">Guardar recurso</button></div></section>`}
window.saveUploadedResource=()=>{let file=document.getElementById('ruFile')?.files?.[0],title=(document.getElementById('ruTitle')?.value||'').trim();if(!file)return alert('Seleccione primero un archivo PDF.');if(!title)return alert('Escriba el título del recurso.');if(file.size>4.5*1024*1024)return alert('Para esta prueba local use un PDF de hasta 4,5 MB.');let rd=new FileReader();rd.onload=()=>{let r={id:'res-'+Date.now(),titulo:title,categoria:document.getElementById('ruCat').value,libro:document.getElementById('ruBook').value,descripcion:document.getElementById('ruDesc').value,fecha:document.getElementById('ruDate').value,destacado:document.getElementById('ruFeatured').checked,tamano:(file.size/1024/1024).toFixed(2)+' MB',archivo:rd.result,nombre:file.name};let all=loadLocalResources();if(r.destacado)all.forEach(x=>x.destacado=false);all.push(r);ministryResources=all;try{saveLocalResources();resourcesPage()}catch(e){alert('El navegador no tiene espacio suficiente para guardar este PDF.')}};rd.readAsDataURL(file)}
function findResourceById(id){return ministryResources.find(x=>x.id===id)||publicResources.find(x=>x.id===id)||loadLocalResources().find(x=>x.id===id)}
window.viewResource=id=>{let r=findResourceById(id);if(!r)return alert('El recurso no está disponible.');let source=r.archivo||r.url;if(!source)return alert('El archivo no está disponible.');window.open(source,'_blank')}
window.downloadResource=id=>{let r=findResourceById(id);if(!r)return alert('El recurso no está disponible.');let source=r.archivo||r.url;if(!source)return alert('El archivo no está disponible.');let a=document.createElement('a');a.href=source;a.download=r.nombre||((r.titulo||'recurso')+'.pdf');a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove()}
window.deleteResource=id=>{if(!isAdminMode()){alert('Esta función está disponible únicamente en modo administrador.');return}if(!confirm('¿Eliminar este recurso?'))return;ministryResources=loadLocalResources().filter(x=>x.id!==id);saveLocalResources();resourcesPage()}

fetch('data/resources.json').then(r=>r.ok?r.json():[]).then(v=>{publicResources=Array.isArray(v)?v:[];if(document.getElementById('resourceResults'))resourcesPage()}).catch(()=>{publicResources=[]});

let ministryVideos=[];
let videoFilter='todos';
const VIDEO_STORE_KEY='ministerio_videos_local_v201';
function loadLocalVideos(){try{return JSON.parse(localStorage.getItem(VIDEO_STORE_KEY)||'[]')}catch(e){return []}}
function saveLocalVideos(){localStorage.setItem(VIDEO_STORE_KEY,JSON.stringify(ministryVideos.filter(v=>v.local)))}
let publicVideos=[];
function syncVideoCatalog(){const local=loadLocalVideos();ministryVideos=[...publicVideos,...local.filter(l=>!publicVideos.some(b=>b.id===l.id))]}
fetch('data/videos.json').then(r=>r.ok?r.json():[]).then(v=>{publicVideos=Array.isArray(v)?v:[];syncVideoCatalog();if(document.getElementById('videoResults'))renderVideos()}).catch(()=>{publicVideos=[];syncVideoCatalog();if(document.getElementById('videoResults'))renderVideos()});
function videoThumb(v){return v.miniatura||'assets/video-placeholder.svg'}
function videoCats(){return ['todos',...new Set(ministryVideos.map(v=>v.categoria).filter(Boolean))]}
window.videosPage=()=>{videoFilter='todos';syncVideoCatalog();app.innerHTML=`<section class="videoHero"><div><span class="badge">🎥 VIDEOTECA DEL MINISTERIO</span><h1>Mensajes para escuchar, compartir<br>y llevar a la vida.</h1><p>Videos terminados del ministerio, reunidos en un solo lugar.</p>${isAdminMode()?`<button class="btn videoAddBtn" onclick="openVideoUploader()">＋ Agregar video</button>`:''}</div></section><section class="videoToolbar"><input id="videoSearch" placeholder="Buscar videos..." oninput="renderVideos()"><div id="videoFilters"></div></section><div id="videoResults"></div>`;renderVideos();enforceVisitorPermissions()}
window.openVideoUploader=()=>{if(!isAdminMode()){alert('Esta función está disponible únicamente en modo administrador.');return}app.innerHTML=`<section class="videoUploadPage"><button class="btn secondary" onclick="videosPage()">← Volver a Videoteca</button><div class="videoUploadCard"><span class="badge">🎥 NUEVO VIDEO</span><h1>Agregar un video terminado</h1><p>Seleccione el MP4 que ya produjo y complete sus datos.</p><label>Archivo MP4<input id="vuFile" type="file" accept="video/mp4,video/*"></label><label>Título<input id="vuTitle" placeholder="Título del video"></label><div class="videoFormGrid"><label>Categoría<select id="vuCat"><option>Enseñanza</option><option>Libro</option><option>Píldora</option><option>Serie</option><option>Mensaje especial</option></select></label><label>Duración<input id="vuDuration" placeholder="Ej. 5:12"></label></div><label>Descripción<textarea id="vuDesc" rows="4"></textarea></label><div class="videoFormGrid"><label>Libro relacionado (opcional)<input id="vuBook"></label><label>Capítulo (opcional)<input id="vuChapter"></label></div><div class="videoFormGrid"><label>Referencia bíblica (opcional)<input id="vuRef"></label><label>Fecha<input id="vuDate" type="date"></label></div><label class="checkLine"><input id="vuFeatured" type="checkbox"> Marcar como video destacado</label><div class="videoUploadNotice"><b>Prueba local:</b> el MP4 queda guardado solamente en este navegador/equipo. Cuando publiquemos el Portal, usaremos alojamiento público para que todos puedan verlo sin volver pesada la Biblioteca.</div><button class="btn" onclick="saveUploadedVideo()">Guardar en la Videoteca</button></div></section>`}
window.saveUploadedVideo=()=>{let file=document.getElementById('vuFile')?.files?.[0],title=(document.getElementById('vuTitle')?.value||'').trim();if(!file)return alert('Seleccione primero el archivo de video.');if(!title)return alert('Escriba el título del video.');if(file.size>4.5*1024*1024)return alert('Para esta prueba local use un MP4 de hasta 4,5 MB. Los videos normales se alojarán externamente al publicar el Portal.');let rd=new FileReader();rd.onload=()=>{let v={id:'local-'+Date.now(),titulo:title,categoria:document.getElementById('vuCat').value,duracion:document.getElementById('vuDuration').value,descripcion:document.getElementById('vuDesc').value,libro:document.getElementById('vuBook').value,capitulo:document.getElementById('vuChapter').value,referencia:document.getElementById('vuRef').value,fecha:document.getElementById('vuDate').value,destacado:document.getElementById('vuFeatured').checked,archivo:rd.result,local:true};if(v.destacado)ministryVideos.forEach(x=>x.destacado=false);ministryVideos.push(v);try{saveLocalVideos();videosPage()}catch(e){ministryVideos.pop();alert('El navegador no tiene espacio suficiente para guardar este MP4.')}};rd.readAsDataURL(file)}
window.playMinistryVideo=()=>{const el=document.getElementById('activeMinistryVideo');if(!el)return;el.play().catch(()=>alert('No fue posible iniciar este archivo. Compruebe que el video sea MP4 compatible con el navegador.'))}
window.deleteLocalVideo=id=>{if(!isAdminMode()){alert('Esta función está disponible únicamente en modo administrador.');return}let v=ministryVideos.find(x=>x.id===id);if(!v?.local)return;if(!confirm('¿Eliminar este video de la Videoteca? Esta acción liberará el espacio que ocupa en este navegador.'))return;ministryVideos=ministryVideos.filter(x=>x.id!==id);try{saveLocalVideos()}catch(e){};alert('Video eliminado. Ya puede subir otro.');videosPage()}
window.setVideoFilter=(el,val)=>{videoFilter=val;document.querySelectorAll('.videoFilter').forEach(x=>x.classList.remove('active'));el.classList.add('active');renderVideos();enforceVisitorPermissions()}
window.renderVideos=()=>{let filters=document.getElementById('videoFilters');if(filters)filters.innerHTML=videoCats().map((c,i)=>`<button class="videoFilter ${videoFilter===c?'active':''}" onclick="setVideoFilter(this,${JSON.stringify(c)})">${c==='todos'?'Todos':esc(c)}</button>`).join('');let q=(document.getElementById('videoSearch')?.value||'').trim().toLowerCase();let rows=ministryVideos.filter(v=>(videoFilter==='todos'||v.categoria===videoFilter)&&(!q||`${v.titulo||''} ${v.descripcion||''} ${v.libro||''} ${v.categoria||''}`.toLowerCase().includes(q)));let host=document.getElementById('videoResults');if(!host)return;if(!ministryVideos.length){host.innerHTML=`<section class="videoEmpty"><div class="videoEmptyIcon">▶</div><h2>La Videoteca está lista</h2><p>Aquí aparecerán los videos terminados que usted vaya incorporando al Portal. La producción permanece independiente en CONSTRUCTOR-VIDEO.</p><div class="videoEmptySteps"><span>1. Produzca el video</span><b>→</b><span>2. Exporte el MP4</span><b>→</b><span>3. Agréguelo aquí</span></div><button class="btn" onclick="openVideoUploader()">＋ Agregar mi primer video</button><small>No se ha incluido ningún video de demostración para evitar publicar contenido ficticio.</small></section>`;return}let featured=rows.find(v=>v.destacado)||rows[0];let rest=rows.filter(v=>!featured||v.id!==featured.id);host.innerHTML=`${featured?`<section class="videoFeatured"><h2>✦ Video destacado</h2><article onclick="openVideo('${String(featured.id).replace(/'/g,"\\'")}')"><div class="videoPoster"><img src="${esc(videoThumb(featured))}" alt=""><button class="playCircle videoPlayButton" type="button" aria-label="Abrir y reproducir video" onclick="event.stopPropagation();openVideo('${String(featured.id).replace(/'/g,"\\'")}')">▶</button>${featured.duracion?`<i>${esc(featured.duracion)}</i>`:''}</div><div><span class="videoTag">${esc(featured.categoria||'Video')}</span><h3>${esc(featured.titulo)}</h3><p>${esc(featured.descripcion||'')}</p>${featured.libro?`<small>Relacionado con ${esc(featured.libro)}</small>`:''}</div></article></section>`:''}<section class="videoList"><div class="videoListHead"><h2>${featured?'Más recientes':'Videos'}</h2><span>${rows.length} video${rows.length===1?'':'s'}</span></div><div class="videoGrid">${rest.map(v=>`<article class="videoCard" onclick="openVideo('${String(v.id).replace(/'/g,"\\'")}')"><div class="videoPoster"><img src="${esc(videoThumb(v))}" alt=""><span class="playCircle small">▶</span>${v.duracion?`<i>${esc(v.duracion)}</i>`:''}</div><span class="videoTag">${esc(v.categoria||'Video')}</span><h3>${esc(v.titulo)}</h3><p>${esc(v.descripcion||'')}</p>${v.libro?`<small>${esc(v.libro)}</small>`:''}</article>`).join('')}</div></section>`}
window.openVideo=id=>{let v=ministryVideos.find(x=>x.id===id);if(!v)return videosPage();let related=ministryVideos.filter(x=>x.id!==id&&(v.libro&&x.libro===v.libro)).slice(0,3);app.innerHTML=`<article class="videoDetail"><button class="btn secondary" onclick="videosPage()">← Videoteca</button><div class="videoPlayer">${(v.archivo||v.url)?`<video id="activeMinistryVideo" controls playsinline preload="metadata" src="${v.archivo||v.url}">Su navegador no puede reproducir este video.</video>`:`<div class="videoNoFile"><span>▶</span><p>Video no disponible.</p></div>`}</div><div class="videoDetailBody"><span class="videoTag">${esc(v.categoria||'Video')}</span><h1>${esc(v.titulo)}</h1><div class="videoMeta">${v.duracion?`▶ ${esc(v.duracion)}`:''}${v.fecha?` <span>·</span> 📅 ${esc(v.fecha)}`:''}</div><div class="videoActions"><button class="btn" onclick="playMinistryVideo()">▶ Reproducir</button><button class="btn secondary" onclick="shareVideo('${String(v.id).replace(/'/g,"\\'")}')">↗ Compartir</button>${v.local&&isAdminMode()?`<button class="btn danger" onclick="deleteLocalVideo('${String(v.id).replace(/'/g,"\\'")}')">🗑 Eliminar video</button>`:''}</div>${v.descripcion?`<section><h2>Descripción</h2><p>${esc(v.descripcion)}</p></section>`:''}${v.referencia?`<section class="videoScripture"><h2>📖 Texto bíblico central</h2><b>${esc(v.referencia)}</b>${v.versiculo?`<p>“${esc(v.versiculo)}”</p>`:''}</section>`:''}${v.libro?`<section class="videoRelatedBook"><h2>📚 Relacionado</h2><div><strong>${esc(v.libro)}</strong>${v.capitulo?`<span>${esc(v.capitulo)}</span>`:''}${v.bookId&&v.sectionId?`<button class="btn secondary" onclick="goToSection('${esc(v.bookId)}','${esc(v.sectionId)}')">Ir al libro →</button>`:''}</div></section>`:''}${related.length?`<section><h2>Más videos de este libro</h2><div class="videoGrid compact">${related.map(x=>`<article class="videoCard" onclick="openVideo('${String(x.id).replace(/'/g,"\\'")}')"><div class="videoPoster"><img src="${esc(videoThumb(x))}" alt=""><span class="playCircle small">▶</span></div><h3>${esc(x.titulo)}</h3></article>`).join('')}</div></section>`:''}</div></article>`}
window.shareVideo=async id=>{let v=ministryVideos.find(x=>x.id===id);if(!v)return;let msg=`${v.titulo}\n${v.descripcion||''}`.trim();if(navigator.share){try{await navigator.share({title:v.titulo,text:msg});return}catch(e){}}try{await navigator.clipboard.writeText(msg);alert('Información del video copiada.')}catch(e){alert(msg)}}
