(()=>{
'use strict';
const $=id=>document.getElementById(id), esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10); const addDays=(d,n)=>{let x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
function ensure(){if(typeof db!=='undefined'&&!Array.isArray(db.commitments))db.commitments=[]}
function save(){if(typeof saveDB==='function')saveDB(); renderAgenda()}
function refs(){return {leaders:db?.leaders||[],needs:db?.needs||[],projects:db?.projects||[],businesses:db?.businesses||[]}}
function options(arr,label){return '<option value="">Sin vincular</option>'+arr.map(x=>`<option value="${esc2(x.id)}">${esc2(label(x))}</option>`).join('')}
function createModal(){if($('commitmentModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="commitmentModal"><div class="modal-card"><div class="modal-head"><div><h3>🤝 Nuevo compromiso</h3><p class="petition-subtitle">Registre qué se acordó, con quién, responsable y fecha límite.</p></div><button type="button" data-commit-close>×</button></div><form id="commitmentForm" class="form-grid"><input type="hidden" name="id"><label class="span-2">Compromiso<textarea name="title" required placeholder="Ej.: Gestionar visita técnica para la vía..."></textarea></label><label>Fecha adquirida<input type="date" name="startDate" required></label><label>Fecha límite<input type="date" name="dueDate" required></label><label>Estado<select name="status"><option>Pendiente</option><option>En gestión</option><option>Cumplido</option><option>No viable</option></select></label><label>Responsable<input name="responsible" placeholder="Equipo / persona responsable"></label><label>Vereda / territorio<input name="territory"></label><label>Contacto relacionado<select name="leaderId" id="commitLeader"></select></label><label>Necesidad relacionada<select name="needId" id="commitNeed"></select></label><label>Proyecto relacionado<select name="projectId" id="commitProject"></select></label><label>Empresa relacionada<select name="businessId" id="commitBusiness"></select></label><label class="span-2">Resultado / evidencia / observaciones<textarea name="notes" placeholder="Avances, radicados, resultado obtenido, evidencia..."></textarea></label><div class="span-2 form-actions"><button class="primary" type="submit">Guardar compromiso</button><button class="secondary" type="button" data-commit-close>Cancelar</button></div></form></div></div>`)}
function fillRefs(){let r=refs();$('commitLeader').innerHTML=options(r.leaders,x=>x.name||x.fullName||'Contacto');$('commitNeed').innerHTML=options(r.needs,x=>`${x.code||''} ${x.title||''}`);$('commitProject').innerHTML=options(r.projects,x=>x.name||'Proyecto');$('commitBusiness').innerHTML=options(r.businesses,x=>x.name||'Empresa')}
function openCommit(c){ensure();fillRefs();let f=$('commitmentForm');f.reset();f.elements.startDate.value=today(); if(c){Object.keys(c).forEach(k=>{if(f.elements[k])f.elements[k].value=c[k]??''})} $('commitmentModal').classList.add('open')}
function close(){ $('commitmentModal')?.classList.remove('open') }
function related(c){let r=refs(), bits=[];let l=r.leaders.find(x=>x.id===c.leaderId),n=r.needs.find(x=>x.id===c.needId),p=r.projects.find(x=>x.id===c.projectId),b=r.businesses.find(x=>x.id===c.businessId);if(l)bits.push(l.name||l.fullName);if(n)bits.push(n.code||n.title);if(p)bits.push(p.name);if(b)bits.push(b.name);return bits.join(' · ')||c.territory||'—'}
function stateClass(s){return s==='Cumplido'?'done':s==='No viable'?'muted':s==='En gestión'?'progress':'pending'}
function agendaItems(){ensure();let t=today(), arr=[];(db.actions||[]).filter(a=>a.nextDate&&a.nextAction).forEach(a=>arr.push({date:a.nextDate,type:'Gestión',title:a.nextAction,sub:a.responsible||'',status:a.nextDate<t?'Vencida':'Programada',go:'actions'}));(db.commitments||[]).filter(c=>c.status!=='Cumplido'&&c.status!=='No viable').forEach(c=>arr.push({date:c.dueDate,type:'Compromiso',title:c.title,sub:related(c),status:c.dueDate<t?'Vencido':c.status,commit:c}));return arr.sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'))}
function renderAgenda(){if(!$('agendaList')||typeof db==='undefined')return;ensure();let t=today(),week=addDays(t,7),items=agendaItems(),over=items.filter(x=>x.date<t).length,todayN=items.filter(x=>x.date===t).length,weekN=items.filter(x=>x.date>=t&&x.date<=week).length,open=(db.commitments||[]).filter(x=>!['Cumplido','No viable'].includes(x.status)).length;$('agendaKpis').innerHTML=`<div class="agenda-kpi danger"><span>Vencidos</span><strong>${over}</strong></div><div class="agenda-kpi"><span>Para hoy</span><strong>${todayN}</strong></div><div class="agenda-kpi"><span>Próximos 7 días</span><strong>${weekN}</strong></div><div class="agenda-kpi"><span>Compromisos abiertos</span><strong>${open}</strong></div>`;let filter=$('agendaFilter')?.value||'all';let shown=items.filter(x=>filter==='all'||(filter==='overdue'&&x.date<t)||(filter==='week'&&x.date>=t&&x.date<=week)||(filter==='commit'&&x.type==='Compromiso')||(filter==='action'&&x.type==='Gestión'));$('agendaList').innerHTML=shown.length?shown.map(x=>`<div class="agenda-row ${x.date<t?'overdue':''}"><div class="agenda-date"><strong>${esc2(x.date||'—')}</strong><span>${esc2(x.type)}</span></div><div class="agenda-main"><b>${esc2(x.title)}</b><small>${esc2(x.sub||'')}</small></div><span class="agenda-status">${esc2(x.status)}</span><div class="agenda-row-actions">${x.commit?`<button class="icon-btn" data-edit-commit="${esc2(x.commit.id)}">✏️</button>`:`<button class="icon-btn" data-go-actions>↗</button>`}</div></div>`).join(''):'<div class="agenda-empty">No hay pendientes en este filtro.</div>';
let cs=(db.commitments||[]).slice().sort((a,b)=>(a.dueDate||'').localeCompare(b.dueDate||''));$('commitmentsTable').innerHTML=`<table><thead><tr><th>Fecha límite</th><th>Compromiso</th><th>Relacionado con</th><th>Responsable</th><th>Estado</th><th></th></tr></thead><tbody>${cs.map(c=>`<tr><td>${esc2(c.dueDate)}</td><td>${esc2(c.title)}</td><td>${esc2(related(c))}</td><td>${esc2(c.responsible||'—')}</td><td><span class="commit-state ${stateClass(c.status)}">${esc2(c.status)}</span></td><td><button class="icon-btn" data-edit-commit="${esc2(c.id)}">✏️</button> <button class="icon-btn" data-del-commit="${esc2(c.id)}">🗑️</button></td></tr>`).join('')||'<tr><td colspan="6">Sin compromisos registrados.</td></tr>'}</tbody></table>`}
function bind(){createModal();ensure();$('newCommitmentBtn')?.addEventListener('click',()=>openCommit());$('agendaFilter')?.addEventListener('change',renderAgenda);document.querySelectorAll('[data-commit-close]').forEach(b=>b.addEventListener('click',close));$('commitmentModal')?.addEventListener('click',e=>{if(e.target===$('commitmentModal'))close()});$('commitmentForm')?.addEventListener('submit',e=>{e.preventDefault();let o=Object.fromEntries(new FormData(e.target));if(o.id){let i=db.commitments.findIndex(x=>x.id===o.id);if(i>=0)db.commitments[i]={...db.commitments[i],...o,updated:new Date().toISOString()}}else db.commitments.push({...o,id:`C-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`,created:new Date().toISOString()});close();save();if(typeof toast==='function')toast('Compromiso guardado')});document.addEventListener('click',e=>{let b=e.target.closest('[data-edit-commit]');if(b){let c=db.commitments.find(x=>x.id===b.dataset.editCommit);if(c)openCommit(c);return}b=e.target.closest('[data-del-commit]');if(b&&confirm('¿Eliminar este compromiso?')){db.commitments=db.commitments.filter(x=>x.id!==b.dataset.delCommit);save();return}if(e.target.closest('[data-go-actions]')&&typeof showView==='function')showView('actions')});document.querySelectorAll('[data-view="agenda"]').forEach(b=>b.addEventListener('click',()=>setTimeout(renderAgenda,0)));window.addEventListener('storage',renderAgenda);renderAgenda()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
