const APP_KEY='matriz_giron_v1';
const sectors=['Infraestructura y vías','Agua y saneamiento','Vivienda','Servicios públicos','Salud','Educación','Deporte y recreación','Seguridad','Ambiente y gestión del riesgo','Desarrollo rural','Desarrollo social','Cultura','Empleo y emprendimiento','Turismo','Movilidad y transporte','Otro'];
const priorities=['Urgente','Alta','Media','Baja'];
const statuses=['Pendiente de verificar','Verificada','Requiere visita técnica','Información insuficiente','Existe proyecto relacionado','En gestión','Solucionada'];
const maturity=['Nivel 1 - Necesidad identificada','Nivel 2 - Necesidad verificada','Nivel 3 - Alternativa de solución identificada','Nivel 4 - En estructuración','Nivel 5 - Proyecto estructurado','Nivel 6 - Proyecto radicado','Nivel 7 - En evaluación','Nivel 8 - Viable','Nivel 9 - Financiado','Nivel 10 - En ejecución','Nivel 11 - Ejecutado','Nivel 12 - Impacto verificado'];
let deferredPrompt=null;
let db=loadDB();

function blankDB(){return {needs:[],leaders:[],projects:[],actions:[],settings:{orgName:'Matriz Maestra de Gestión Territorial para Girón',orgTeam:''}}}
function loadDB(){try{return {...blankDB(),...JSON.parse(localStorage.getItem(APP_KEY)||'{}')}}catch(e){return blankDB()}}
function saveDB(){localStorage.setItem(APP_KEY,JSON.stringify(db));renderAll()}
function uid(prefix){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`}
function needCode(){const year=new Date().getFullYear();const n=(db.needs.length+1).toString().padStart(4,'0');return `GIRON-${year}-${n}`}
function money(v){return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v||0))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function tag(text){const t=(text||'').toLowerCase();let c='gray';if(t.includes('urgente')||t.includes('detenido'))c='red';else if(t.includes('alta')||t.includes('ajuste')||t.includes('visita'))c='orange';else if(t.includes('media')||t.includes('evaluación')||t.includes('pendiente'))c='yellow';else if(t.includes('solucion')||t.includes('viable')||t.includes('financiado')||t.includes('verificada'))c='green';else if(t.includes('gestión')||t.includes('proyecto'))c='blue';return `<span class="tag ${c}">${esc(text)}</span>`}
function fillSelect(id,arr,blank){const el=document.getElementById(id);if(!el)return;el.innerHTML=(blank?`<option value="">${blank}</option>`:'')+arr.map(x=>`<option>${esc(x)}</option>`).join('')}

function init(){
  fillSelect('needSector',sectors);fillSelect('projectSector',sectors);fillSelect('communitySector',sectors);
  fillSelect('needPriority',priorities);fillSelect('needStatus',statuses);fillSelect('needMaturity',maturity);
  fillSelect('needStatusFilter',statuses,'Todos los estados');fillSelect('needPriorityFilter',priorities,'Todas las prioridades');
  document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  document.querySelectorAll('[data-open-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.openModal)));
  document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeModals));
  document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));
  bindForms();bindButtons();renderAll();registerSW();
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.remove('hidden')});
  document.getElementById('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById('installBtn').classList.add('hidden')});
}
function showView(v){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(`view-${v}`).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function openModal(id){refreshRefs();document.getElementById(id).classList.add('open')}
function closeModals(){document.querySelectorAll('.modal').forEach(m=>m.classList.remove('open'))}

function bindForms(){
 document.getElementById('needForm').addEventListener('submit',e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));if(o.id){const i=db.needs.findIndex(x=>x.id===o.id);db.needs[i]={...db.needs[i],...o}}else db.needs.push({...o,id:uid('N'),code:needCode(),created:new Date().toISOString()});e.target.reset();closeModals();saveDB();toast('Necesidad guardada')});
 document.getElementById('leaderForm').addEventListener('submit',e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));if(o.id){const i=db.leaders.findIndex(x=>x.id===o.id);db.leaders[i]={...db.leaders[i],...o}}else db.leaders.push({...o,id:uid('L'),created:new Date().toISOString()});e.target.reset();closeModals();saveDB();toast('Contacto guardado')});
 document.getElementById('projectForm').addEventListener('submit',e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));if(o.id){const i=db.projects.findIndex(x=>x.id===o.id);db.projects[i]={...db.projects[i],...o}}else db.projects.push({...o,id:uid('P'),created:new Date().toISOString()});e.target.reset();closeModals();saveDB();toast('Proyecto guardado')});
 document.getElementById('actionForm').addEventListener('submit',e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));if(o.id){const i=db.actions.findIndex(x=>x.id===o.id);db.actions[i]={...db.actions[i],...o}}else db.actions.push({...o,id:uid('A'),created:new Date().toISOString()});const n=db.needs.find(x=>x.id===o.needId);if(n){n.nextAction=o.nextAction||n.nextAction;n.responsible=o.responsible||n.responsible;n.followUp=o.nextDate||n.followUp;n.status=n.status==='Solucionada'?n.status:'En gestión'}e.target.reset();closeModals();saveDB();toast('Gestión registrada')});
 document.getElementById('communityForm').addEventListener('submit',e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const leader=db.leaders.find(l=>l.id===o.leaderId);if(!leader){toast('Seleccione un líder / JAC / Edil registrado');return}const need={id:uid('N'),code:needCode(),territory:o.territory,zone:o.zone,title:o.title,sector:o.sector,priority:o.priority,status:'Pendiente de verificar',maturity:maturity[0],leaderId:leader.id,competentEntity:'',location:o.location,description:`Importancia: ${o.importance||''}\nProyecto existente: ${o.existingProject||''}\nGestiones previas: ${o.previous||''}`,affected:o.affected,age:o.age,evidence:'Fotografías registradas desde formulario comunitario',nextAction:'Verificar necesidad y definir entidad competente',responsible:'',followUp:'',created:new Date().toISOString()};db.needs.push(need);window.dispatchEvent(new CustomEvent('community-need-saved',{detail:{needId:need.id}}));e.target.reset();saveDB();toast('Información comunitaria incorporada a la Matriz')});
}
function bindButtons(){
 document.getElementById('needSearch').addEventListener('input',renderNeeds);document.getElementById('needStatusFilter').addEventListener('change',renderNeeds);document.getElementById('needPriorityFilter').addEventListener('change',renderNeeds);
 document.getElementById('backupBtn').onclick=exportJSON;document.getElementById('exportJson').onclick=exportJSON;document.getElementById('importJson').addEventListener('change',importJSON);document.getElementById('exportCsv').onclick=exportCSV;
 document.getElementById('printDiagnosis').onclick=()=>printReport('diagnosis');document.getElementById('printTerritory').onclick=()=>printReport('territory');
 document.getElementById('saveSettings').onclick=()=>{db.settings.orgName=document.getElementById('orgName').value;db.settings.orgTeam=document.getElementById('orgTeam').value;saveDB();toast('Configuración guardada')};
 document.getElementById('clearData').onclick=()=>{if(confirm('¿Seguro que desea borrar todos los datos locales? Esta acción no se puede deshacer.')){db=blankDB();saveDB();toast('Datos borrados')}};
}
function refreshRefs(){
 const leaderOpts='<option value="">Sin asignar</option>'+db.leaders.map(l=>`<option value="${l.id}">${esc(l.name)} · ${esc(l.territory||'')}</option>`).join('');document.getElementById('needLeader').innerHTML=leaderOpts;
 const communityLeader=document.getElementById('communityLeader');if(communityLeader){const current=communityLeader.value;communityLeader.innerHTML='<option value="">Seleccione un líder registrado</option>'+db.leaders.map(l=>`<option value="${l.id}">${esc(l.name)} · ${esc(l.role||'')} · ${esc(l.territory||'')}</option>`).join('');communityLeader.value=current;}
 const needOpts='<option value="">Sin vincular</option>'+db.needs.map(n=>`<option value="${n.id}">${esc(n.code)} · ${esc(n.title)}</option>`).join('');document.getElementById('projectNeed').innerHTML=needOpts;document.getElementById('actionNeed').innerHTML=needOpts;
 const projectOpts='<option value="">Sin vincular</option>'+db.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');document.getElementById('actionProject').innerHTML=projectOpts;
 const terr=[...new Set(db.needs.map(n=>n.territory).filter(Boolean))].sort();document.getElementById('territoryReport').innerHTML=terr.map(t=>`<option>${esc(t)}</option>`).join('')||'<option>Sin datos</option>';
}
function renderAll(){renderDashboard();renderNeeds();renderLeaders();renderProjects();renderActions();refreshRefs();document.getElementById('orgName').value=db.settings.orgName||'';document.getElementById('orgTeam').value=db.settings.orgTeam||''}
function renderDashboard(){
 const n=db.needs.length, verified=db.needs.filter(x=>x.status==='Verificada'||x.status==='En gestión'||x.status==='Solucionada').length, urgent=db.needs.filter(x=>x.priority==='Urgente').length, projects=db.projects.length, solved=db.needs.filter(x=>x.status==='Solucionada').length, territories=new Set(db.needs.map(x=>x.territory).filter(Boolean)).size;
 const inManagement=db.needs.filter(x=>x.status==='En gestión').length; const overdue=db.needs.filter(x=>x.followUp && x.followUp < new Date().toISOString().slice(0,10) && x.status!=='Solucionada').length; const kpiData=[['♟','Necesidades\nregistradas',n],['✓','Verificadas',verified],['▤','En gestión',inManagement],['📁','Proyectos e\niniciativas',projects],['✓','Solucionadas',solved],['●','Acciones\nvencidas',overdue]]; document.getElementById('kpis').innerHTML=kpiData.map(([i,l,v])=>`<div class="kpi"><div class="ico">${i}</div><div><div class="n">${v}</div><div class="l">${l.replace('\n','<br>')}</div></div><div class="kpi-link">Ver todas</div></div>`).join(''); const total=document.getElementById('totalNeeds'); if(total) total.textContent=n;
 renderBars('statusBars',statuses,db.needs,'status');renderBars('priorityBars',priorities,db.needs,'priority');
 const counts={};db.needs.forEach(x=>counts[x.sector]=(counts[x.sector]||0)+1);document.getElementById('sectorList').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<div class="list-row"><span>${esc(k||'Sin sector')}</span><strong>${v}</strong></div>`).join('')||'<p class="muted">Aún no hay información registrada.</p>';
 const up=db.needs.filter(x=>x.followUp||x.nextAction).sort((a,b)=>(a.followUp||'9999').localeCompare(b.followUp||'9999')).slice(0,7);document.getElementById('upcoming').innerHTML=up.map(x=>`<div class="list-row"><div><strong>${esc(x.code)}</strong> · ${esc(x.title)}<div class="muted">${esc(x.nextAction||'Sin próxima acción')}</div></div><span>${esc(x.followUp||'—')}</span></div>`).join('')||'<p class="muted">No hay seguimientos programados.</p>';
}
function renderBars(id,values,data,key){const max=Math.max(1,...values.map(v=>data.filter(x=>x[key]===v).length));document.getElementById(id).innerHTML=values.map(v=>{const c=data.filter(x=>x[key]===v).length;return `<div class="bar-row"><span>${esc(v)}</span><div class="bar-track"><div class="bar-fill" style="width:${c/max*100}%"></div></div><strong>${c}</strong></div>`}).join('')}
function renderNeeds(){const q=(document.getElementById('needSearch')?.value||'').toLowerCase(),sf=document.getElementById('needStatusFilter')?.value||'',pf=document.getElementById('needPriorityFilter')?.value||'';const rows=db.needs.filter(n=>(!q||[n.code,n.territory,n.title,n.sector].join(' ').toLowerCase().includes(q))&&(!sf||n.status===sf)&&(!pf||n.priority===pf));document.getElementById('needsTable').innerHTML=`<table><thead><tr><th>Código</th><th>Territorio</th><th>Necesidad</th><th>Sector</th><th>Prioridad</th><th>Estado</th><th>Próxima acción</th><th>Seguimiento</th><th></th></tr></thead><tbody>${rows.map(n=>`<tr><td><strong>${esc(n.code)}</strong></td><td>${esc(n.territory)}</td><td>${esc(n.title)}</td><td>${esc(n.sector)}</td><td>${tag(n.priority)}</td><td>${tag(n.status)}</td><td>${esc(n.nextAction||'—')}</td><td>${esc(n.followUp||'—')}</td><td><button class="icon-btn" onclick="editNeed('${n.id}')">✏️</button><button class="icon-btn" onclick="deleteItem('needs','${n.id}')">🗑️</button></td></tr>`).join('')||'<tr><td colspan="9">Sin registros.</td></tr>'}</tbody></table>`}
function renderLeaders(){document.getElementById('leadersTable').innerHTML=`<table><thead><tr><th>Nombre</th><th>Calidad</th><th>Organización</th><th>Territorio</th><th>WhatsApp</th><th>Comunicaciones</th><th>Último contacto</th><th>Necesidades</th><th></th></tr></thead><tbody>${db.leaders.map(l=>{const consent=l.communicationsConsent||'Pendiente';const wa=l.whatsapp||l.phone||'';const waBtn=(consent==='Sí'&&wa)?`<button class="icon-btn wa-contact-btn" title="Abrir WhatsApp" onclick="openLeaderWhatsApp('${l.id}')">🟢</button>`:'';return `<tr><td><strong>${esc(l.name)}</strong></td><td>${esc(l.role)}</td><td>${esc(l.organization||'—')}</td><td>${esc(l.territory||'—')}</td><td>${esc(wa||'—')} ${waBtn}</td><td>${tag(consent)}</td><td>${esc(l.lastCommunication||'—')}</td><td>${db.needs.filter(n=>n.leaderId===l.id).length}</td><td><button class="icon-btn" onclick="editLeader('${l.id}')">✏️</button><button class="icon-btn" onclick="deleteItem('leaders','${l.id}')">🗑️</button></td></tr>`}).join('')||'<tr><td colspan="9">Sin registros.</td></tr>'}</tbody></table>`;const c=document.getElementById('authorizedContactsCount');if(c)c.textContent=db.leaders.filter(l=>l.communicationsConsent==='Sí').length}
function renderProjects(){document.getElementById('projectsTable').innerHTML=`<table><thead><tr><th>Proyecto</th><th>Territorio</th><th>Sector</th><th>Entidad</th><th>Radicado</th><th>Estado</th><th>Valor</th><th>Necesidad vinculada</th><th></th></tr></thead><tbody>${db.projects.map(p=>{const n=db.needs.find(x=>x.id===p.needId);return `<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.territory||'—')}</td><td>${esc(p.sector||'—')}</td><td>${esc(p.entity||'—')}</td><td>${esc(p.radicado||'—')}</td><td>${tag(p.status)}</td><td>${money(p.value)}</td><td>${esc(n?.code||'—')}</td><td><button class="icon-btn" onclick="editProject('${p.id}')">✏️</button><button class="icon-btn" onclick="deleteItem('projects','${p.id}')">🗑️</button></td></tr>`}).join('')||'<tr><td colspan="9">Sin registros.</td></tr>'}</tbody></table>`}
function renderActions(){document.getElementById('actionsTable').innerHTML=`<table><thead><tr><th>Fecha</th><th>Necesidad</th><th>Proyecto</th><th>Tipo</th><th>Actuación</th><th>Responsable</th><th>Próxima acción</th><th>Próxima fecha</th><th></th></tr></thead><tbody>${db.actions.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(a=>{const n=db.needs.find(x=>x.id===a.needId),p=db.projects.find(x=>x.id===a.projectId);return `<tr><td>${esc(a.date)}</td><td>${esc(n?.code||'—')}</td><td>${esc(p?.name||'—')}</td><td>${esc(a.type)}</td><td>${esc(a.description)}</td><td>${esc(a.responsible||'—')}</td><td>${esc(a.nextAction||'—')}</td><td>${esc(a.nextDate||'—')}</td><td><button class="icon-btn" onclick="deleteItem('actions','${a.id}')">🗑️</button></td></tr>`}).join('')||'<tr><td colspan="9">Sin registros.</td></tr>'}</tbody></table>`}

window.editNeed=id=>{const n=db.needs.find(x=>x.id===id);openModal('needModal');const f=document.getElementById('needForm');Object.entries(n).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??''})}
window.editLeader=id=>{const n=db.leaders.find(x=>x.id===id);openModal('leaderModal');const f=document.getElementById('leaderForm');Object.entries(n).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??''})}
window.editProject=id=>{const n=db.projects.find(x=>x.id===id);openModal('projectModal');const f=document.getElementById('projectForm');Object.entries(n).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??''})}
window.deleteItem=(col,id)=>{if(confirm('¿Eliminar este registro?')){db[col]=db[col].filter(x=>x.id!==id);saveDB();toast('Registro eliminado')}}

function exportJSON(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});downloadBlob(blob,`MATRIZ-GIRON-RESPALDO-${new Date().toISOString().slice(0,10)}.json`)}
function importJSON(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result);if(!obj.needs||!obj.leaders)throw new Error('Formato inválido');db={...blankDB(),...obj};saveDB();toast('Respaldo restaurado')}catch(err){alert('No fue posible importar el archivo: '+err.message)}};r.readAsText(f);e.target.value=''}
function exportCSV(){const cols=['code','territory','zone','title','sector','priority','status','maturity','competentEntity','location','affected','age','nextAction','responsible','followUp'];const q=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv='\ufeff'+cols.join(';')+'\n'+db.needs.map(n=>cols.map(c=>q(n[c])).join(';')).join('\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),`NECESIDADES-GIRON-${new Date().toISOString().slice(0,10)}.csv`)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function printReport(type){let title='Diagnóstico Territorial de Girón';let items=db.needs;if(type==='territory'){const t=document.getElementById('territoryReport').value;title=`Ficha Territorial · ${t}`;items=db.needs.filter(n=>n.territory===t)}const html=`<html><head><title>${esc(title)}</title><style>body{font-family:Arial;padding:32px;color:#183025}h1{color:#0f5132}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px;text-align:left;font-size:12px}.summary{display:flex;gap:18px;margin:18px 0}.box{border:1px solid #ddd;padding:12px;border-radius:8px}</style></head><body><h1>${esc(title)}</h1><p>Matriz Maestra de Gestión Territorial para Girón</p><div class="summary"><div class="box"><b>Necesidades:</b> ${items.length}</div><div class="box"><b>Urgentes:</b> ${items.filter(x=>x.priority==='Urgente').length}</div><div class="box"><b>En gestión:</b> ${items.filter(x=>x.status==='En gestión').length}</div><div class="box"><b>Solucionadas:</b> ${items.filter(x=>x.status==='Solucionada').length}</div></div><table><tr><th>Código</th><th>Territorio</th><th>Necesidad</th><th>Sector</th><th>Prioridad</th><th>Estado</th><th>Próxima acción</th></tr>${items.map(n=>`<tr><td>${esc(n.code)}</td><td>${esc(n.territory)}</td><td>${esc(n.title)}</td><td>${esc(n.sector)}</td><td>${esc(n.priority)}</td><td>${esc(n.status)}</td><td>${esc(n.nextAction||'')}</td></tr>`).join('')}</table><script>window.print()<\/script></body></html>`;const w=window.open('','_blank');w.document.write(html);w.document.close()}
async function registerSW(){if('serviceWorker' in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await reg.update()}catch(e){console.warn(e)}}}
init();

function updateClock(){const d=new Date();const date=document.getElementById('liveDate'),time=document.getElementById('liveTime');if(date)date.textContent='▣ '+new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'long',year:'numeric'}).format(d);if(time)time.textContent='◷ '+new Intl.DateTimeFormat('es-CO',{hour:'numeric',minute:'2-digit'}).format(d)} updateClock(); setInterval(updateClock,30000);
