(()=>{
'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s??'').trim();
const norm=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const dateLabel=s=>{if(!s)return 'Sin fecha';const d=new Date(s.length===10?s+'T12:00:00':s);return Number.isNaN(d.getTime())?esc(s):d.toLocaleDateString('es-CO',{year:'numeric',month:'short',day:'2-digit'})};
let mode='contact', current='';
function data(){return typeof db!=='undefined'?db:{leaders:[],needs:[],projects:[],actions:[],commitments:[],businesses:[]}}
function terrOf(x){return clean(x?.vereda)||clean(x?.territory)}
function sameTerr(a,b){return !!a&&!!b&&norm(a)===norm(b)}
function openDocs(){return new Promise(res=>{try{const r=indexedDB.open('matriz_giron_documents_v1',1);r.onerror=()=>res([]);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('petitionPdfs'))r.result.createObjectStore('petitionPdfs',{keyPath:'id'})};r.onsuccess=()=>{const x=r.result,tx=x.transaction('petitionPdfs','readonly'),q=tx.objectStore('petitionPdfs').getAll();q.onerror=()=>{x.close();res([])};q.onsuccess=()=>{const out=q.result||[];x.close();res(out)}}}catch(e){res([])}})}
function contactBundle(id,docs){const d=data(),l=(d.leaders||[]).find(x=>x.id===id);if(!l)return null;const needs=(d.needs||[]).filter(n=>n.leaderId===id);const needIds=new Set(needs.map(n=>n.id));const projects=(d.projects||[]).filter(p=>needIds.has(p.needId));const projectIds=new Set(projects.map(p=>p.id));const actions=(d.actions||[]).filter(a=>needIds.has(a.needId)||projectIds.has(a.projectId));const commitments=(d.commitments||[]).filter(c=>c.leaderId===id||needIds.has(c.needId)||projectIds.has(c.projectId));const petitions=docs.filter(p=>needIds.has(p.needId));const territory=terrOf(l);const businesses=(d.businesses||[]).filter(b=>sameTerr(terrOf(b),territory));return {kind:'contact',entity:l,territory,needs,projects,actions,commitments,petitions,businesses}}
function territoryBundle(t,docs){const d=data();const leaders=(d.leaders||[]).filter(l=>sameTerr(terrOf(l),t));const leaderIds=new Set(leaders.map(l=>l.id));const needs=(d.needs||[]).filter(n=>sameTerr(terrOf(n),t)||leaderIds.has(n.leaderId));const needIds=new Set(needs.map(n=>n.id));const projects=(d.projects||[]).filter(p=>sameTerr(terrOf(p),t)||needIds.has(p.needId));const projectIds=new Set(projects.map(p=>p.id));const actions=(d.actions||[]).filter(a=>sameTerr(terrOf(a),t)||needIds.has(a.needId)||projectIds.has(a.projectId));const commitments=(d.commitments||[]).filter(c=>sameTerr(c.territory,t)||leaderIds.has(c.leaderId)||needIds.has(c.needId)||projectIds.has(c.projectId));const businesses=(d.businesses||[]).filter(b=>sameTerr(terrOf(b),t));const petitions=docs.filter(p=>sameTerr(clean(p.vereda)||clean(p.territory),t)||needIds.has(p.needId));return {kind:'territory',entity:{name:t},territory:t,leaders,needs,projects,actions,commitments,petitions,businesses}}
function statusCard(label,n,detail,cls=''){return `<div class="dossier-kpi ${cls}"><strong>${n}</strong><span>${esc(label)}</span><small>${esc(detail||'')}</small></div>`}
function hero(b){if(b.kind==='contact'){const l=b.entity;return `<div class="dossier-hero-main"><div class="dossier-avatar">${esc((l.name||'?').slice(0,1).toUpperCase())}</div><div><span>EXPEDIENTE PERSONAL 360°</span><h2>${esc(l.name||'Contacto')}</h2><p>${esc(l.role||'Contacto territorial')} · ${esc(l.organization||'Sin organización registrada')}</p></div></div><div class="dossier-hero-meta"><span>🏘️ ${esc(b.territory||'Sin territorio')}</span><span>📱 ${esc(l.whatsapp||l.phone||'Sin teléfono')}</span><span>✉️ ${esc(l.email||'Sin correo')}</span><span>💬 Comunicaciones: ${esc(l.communicationsConsent||'Pendiente')}</span></div>`}return `<div class="dossier-hero-main"><div class="dossier-avatar">🏘️</div><div><span>EXPEDIENTE TERRITORIAL 360°</span><h2>${esc(b.territory)}</h2><p>Memoria consolidada de personas, necesidades, proyectos, gestiones y resultados.</p></div></div><div class="dossier-hero-meta"><span>👥 ${(b.leaders||[]).length} contactos</span><span>◆ ${b.needs.length} necesidades</span><span>🏢 ${b.businesses.length} empresas</span><span>📄 ${b.petitions.length} Derechos de Petición</span></div>`}
function timelineRows(b){const rows=[];b.needs.forEach(x=>rows.push({date:x.created?.slice(0,10),type:'Necesidad',icon:'◆',title:x.title,sub:`${x.code||''} · ${x.status||''}`}));b.projects.forEach(x=>rows.push({date:x.radicadoDate||x.created?.slice(0,10),type:'Proyecto',icon:'▣',title:x.name,sub:`${x.entity||'Sin entidad'} · ${x.status||''}`}));b.actions.forEach(x=>rows.push({date:x.date||x.created?.slice(0,10),type:'Gestión',icon:'✓',title:x.description,sub:`${x.type||''}${x.responsible?' · '+x.responsible:''}`}));b.commitments.forEach(x=>rows.push({date:x.startDate||x.created?.slice(0,10),type:'Compromiso',icon:'🤝',title:x.title,sub:`${x.status||''}${x.dueDate?' · vence '+dateLabel(x.dueDate):''}`}));b.petitions.forEach(x=>rows.push({date:(x.radicadoDate||x.generatedAt||'').slice(0,10),type:'Derecho de Petición',icon:'📄',title:x.subject||x.needTitle||'Derecho de Petición',sub:`${x.entity||'Sin entidad'}${x.radicado?' · Rad. '+x.radicado:''}`}));b.businesses.forEach(x=>rows.push({date:x.created?.slice(0,10),type:'Empresa',icon:'🏢',title:x.name,sub:x.contribution||x.sector||'Contando tu historia'}));return rows.filter(x=>x.title).sort((a,b)=>(b.date||'').localeCompare(a.date||''))}
function renderTimeline(b){const rows=timelineRows(b);$('dossierTimeline').innerHTML=rows.length?rows.map(r=>`<div class="dossier-event"><div class="dossier-event-icon">${r.icon}</div><div><time>${dateLabel(r.date)} · ${esc(r.type)}</time><strong>${esc(r.title)}</strong><p>${esc(r.sub||'')}</p></div></div>`).join(''):'<div class="dossier-no-data">Aún no hay eventos vinculados.</div>'}
function renderStatus(b){const openNeeds=b.needs.filter(n=>n.status!=='Solucionada'), solved=b.needs.filter(n=>n.status==='Solucionada'), openCommit=b.commitments.filter(c=>!['Cumplido','No viable'].includes(c.status)), doneCommit=b.commitments.filter(c=>c.status==='Cumplido');const upcoming=[...b.actions.filter(a=>a.nextAction&&a.nextDate).map(a=>({d:a.nextDate,t:a.nextAction})),...openCommit.filter(c=>c.dueDate).map(c=>({d:c.dueDate,t:c.title}))].sort((a,b)=>a.d.localeCompare(b.d)).slice(0,5);$('dossierStatus').innerHTML=`<div class="dossier-status-grid"><div><strong>${openNeeds.length}</strong><span>Necesidades abiertas</span></div><div><strong>${solved.length}</strong><span>Necesidades solucionadas</span></div><div><strong>${openCommit.length}</strong><span>Compromisos abiertos</span></div><div><strong>${doneCommit.length}</strong><span>Compromisos cumplidos</span></div></div><h4>Próximos pasos</h4>${upcoming.length?upcoming.map(x=>`<div class="dossier-next"><b>${dateLabel(x.d)}</b><span>${esc(x.t)}</span></div>`).join(''):'<div class="dossier-no-data">Sin próximas acciones programadas.</div>'}`}
function relSection(title,items,mapper){return `<details class="dossier-rel" ${items.length?'':'disabled'}><summary>${title}<strong>${items.length}</strong></summary><div>${items.length?items.map(mapper).join(''):'<p>Sin registros vinculados.</p>'}</div></details>`}
function renderRelations(b){const leaderRows=b.kind==='territory'?relSection('👥 Contactos',b.leaders,x=>`<article><b>${esc(x.name)}</b><span>${esc(x.role||'')} · ${esc(x.organization||'')}</span></article>`):'';$('dossierRelations').innerHTML=leaderRows+relSection('◆ Necesidades',b.needs,x=>`<article><b>${esc(x.code||'')} · ${esc(x.title)}</b><span>${esc(x.priority||'')} · ${esc(x.status||'')}</span></article>`)+relSection('▣ Proyectos',b.projects,x=>`<article><b>${esc(x.name)}</b><span>${esc(x.entity||'Sin entidad')} · ${esc(x.status||'')}</span></article>`)+relSection('✓ Gestiones',b.actions,x=>`<article><b>${esc(x.type||'Gestión')} · ${dateLabel(x.date)}</b><span>${esc(x.description||'')}</span></article>`)+relSection('🤝 Compromisos',b.commitments,x=>`<article><b>${esc(x.title)}</b><span>${esc(x.status||'')} · ${x.dueDate?'Vence '+dateLabel(x.dueDate):'Sin fecha límite'}</span></article>`)+relSection('📄 Derechos de Petición',b.petitions,x=>`<article><b>${esc(x.needCode||x.subject||'Derecho de Petición')}</b><span>${esc(x.entity||'Sin entidad')}${x.radicado?' · Rad. '+esc(x.radicado):''}</span></article>`)+relSection('🏢 Empresas · Contando tu historia',b.businesses,x=>`<article><b>${esc(x.name)}</b><span>${esc(x.sector||'')} · ${Number(x.jobs||0)} empleos reportados</span></article>`)}
async function render(){const docs=await openDocs();const b=mode==='contact'?contactBundle(current,docs):territoryBundle(current,docs);if(!b){$('dossierEmpty').classList.remove('hidden');$('dossierContent').classList.add('hidden');return}$('dossierEmpty').classList.add('hidden');$('dossierContent').classList.remove('hidden');$('dossierHero').innerHTML=hero(b);$('dossierKpis').innerHTML=[statusCard('Necesidades',b.needs.length,`${b.needs.filter(n=>n.status==='Solucionada').length} solucionadas`),statusCard('Proyectos',b.projects.length,'Vinculados al expediente'),statusCard('Gestiones',b.actions.length,'Actuaciones registradas'),statusCard('Compromisos',b.commitments.length,`${b.commitments.filter(c=>c.status==='Cumplido').length} cumplidos`),statusCard('Derechos de Petición',b.petitions.length,'PDFs archivados'),statusCard('Empresas',b.businesses.length,'Capacidades productivas')].join('');renderTimeline(b);renderStatus(b);renderRelations(b);window.__dossierCurrent=b}
function populate(){const d=data(),cs=$('dossierContactSelect'),ts=$('dossierTerritorySelect');if(cs){const cur=cs.value;cs.innerHTML='<option value="">Seleccione un contacto</option>'+[...(d.leaders||[])].sort((a,b)=>clean(a.name).localeCompare(clean(b.name),'es')).map(l=>`<option value="${esc(l.id)}">${esc(l.name)} · ${esc(terrOf(l)||'Sin territorio')}</option>`).join('');if([...cs.options].some(o=>o.value===cur))cs.value=cur}if(ts){const vals=[...new Set([...(d.leaders||[]).map(terrOf),...(d.needs||[]).map(terrOf),...(d.projects||[]).map(terrOf),...(d.businesses||[]).map(terrOf),(d.commitments||[]).map(x=>clean(x.territory))].flat().filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));const cur=ts.value;ts.innerHTML='<option value="">Seleccione un territorio</option>'+vals.map(t=>`<option>${esc(t)}</option>`).join('');if(vals.includes(cur))ts.value=cur}}
function setMode(m){mode=m;current='';document.querySelectorAll('.dossier-mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.dossierMode===m));$('dossierContactLabel').classList.toggle('hidden',m!=='contact');$('dossierTerritoryLabel').classList.toggle('hidden',m!=='territory');$('dossierEmpty').classList.remove('hidden');$('dossierContent').classList.add('hidden')}
function printCurrent(){const b=window.__dossierCurrent;if(!b){alert('Seleccione primero un expediente.');return}const title=b.kind==='contact'?`Expediente 360° · ${b.entity.name}`:`Expediente Territorial 360° · ${b.territory}`;const events=timelineRows(b);const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:Arial,sans-serif;color:#17324d;padding:30px}h1{color:#062a52;margin-bottom:4px}.sub{color:#607080;margin-bottom:24px}.k{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.k div{border:1px solid #d9e2ea;border-radius:10px;padding:12px}.k b{font-size:24px;display:block}.ev{border-left:3px solid #0f6c5c;padding:0 0 14px 14px;margin-left:8px}.ev small{color:#607080}table{width:100%;border-collapse:collapse;margin-top:15px}th,td{border:1px solid #ddd;padding:7px;text-align:left;font-size:12px}@media print{button{display:none}}</style></head><body><h1>${esc(title)}</h1><div class="sub">Matriz Maestra de Gestión Territorial para Girón · Generado ${new Date().toLocaleString('es-CO')}</div><div class="k"><div><b>${b.needs.length}</b>Necesidades</div><div><b>${b.projects.length}</b>Proyectos</div><div><b>${b.actions.length}</b>Gestiones</div><div><b>${b.commitments.length}</b>Compromisos</div><div><b>${b.petitions.length}</b>Derechos de Petición</div><div><b>${b.businesses.length}</b>Empresas</div></div><h2>Línea de tiempo</h2>${events.map(e=>`<div class="ev"><small>${dateLabel(e.date)} · ${esc(e.type)}</small><br><b>${esc(e.title)}</b><br>${esc(e.sub||'')}</div>`).join('')||'<p>Sin eventos.</p>'}<script>window.print()<\/script></body></html>`;const w=window.open('','_blank');w.document.write(html);w.document.close()}
function bind(){populate();document.querySelectorAll('.dossier-mode-btn').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.dossierMode)));$('dossierContactSelect')?.addEventListener('change',e=>{current=e.target.value;render()});$('dossierTerritorySelect')?.addEventListener('change',e=>{current=e.target.value;render()});$('dossierPrintBtn')?.addEventListener('click',printCurrent);document.querySelectorAll('[data-view="dossier"]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{populate();if(current)render()},0)));window.addEventListener('storage',()=>{populate();if(current)render()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
