(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const getDB=()=>{ try{return JSON.parse(localStorage.getItem('matriz_giron_v1')||'{}')}catch(e){return {}} };
const arr=(db,k)=>Array.isArray(db?.[k])?db[k]:[];
function countsBy(items,field){const o={};items.forEach(x=>{const k=x?.[field]||'Sin definir';o[k]=(o[k]||0)+1});return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function bars(rows,total){if(!rows.length)return '<div class="intel-empty">Aún no hay información registrada.</div>';return `<div class="intel-bars">${rows.slice(0,8).map(([n,c])=>`<div class="intel-bar-row"><span>${esc(n)}</span><div class="intel-track"><i style="width:${total?Math.max(3,c/total*100):0}%"></i></div><b>${c}</b></div>`).join('')}</div>`}
function render(){
 const db=getDB(),needs=arr(db,'needs'),leaders=arr(db,'leaders'),projects=arr(db,'projects'),actions=arr(db,'actions');
 const territories=[...new Set(needs.map(n=>n.territory).filter(Boolean))].sort();
 if($('intelKpis'))$('intelKpis').innerHTML=[
  [needs.length,'Necesidades'],[needs.filter(n=>n.status==='Pendiente de verificar').length,'Pendientes'],[needs.filter(n=>n.status==='En gestión').length,'En gestión'],[needs.filter(n=>n.status==='Solucionada').length,'Solucionadas'],[leaders.length,'Líderes / JAC / Ediles'],[territories.length,'Territorios cubiertos']
 ].map(([n,t])=>`<div class="intel-kpi"><strong>${n}</strong><span>${t}</span></div>`).join('');
 if($('intelDiagnosis'))$('intelDiagnosis').innerHTML=`<h4>Por sector</h4>${bars(countsBy(needs,'sector'),needs.length)}<h4>Por prioridad</h4>${bars(countsBy(needs,'priority'),needs.length)}<h4>Por estado</h4>${bars(countsBy(needs,'status'),needs.length)}`;
 const sel=$('intelTerritorySelect');if(sel){const current=sel.value;sel.innerHTML=territories.length?territories.map(t=>`<option>${esc(t)}</option>`).join(''):'<option value="">Sin datos</option>';if(current&&territories.includes(current))sel.value=current;}
 renderTerritory();
 const advanced=needs.filter(n=>!['Pendiente de verificar','Información insuficiente'].includes(n.status)).length;
 const managedIds=new Set(actions.map(a=>a.needId).filter(Boolean));
 const projIds=new Set(projects.map(p=>p.needId).filter(Boolean));
 if($('intelManagement'))$('intelManagement').innerHTML=`<div class="intel-flow">${[[needs.length,'Identificadas'],[advanced,'Verificadas / avanzadas'],[managedIds.size,'Con gestión'],[projIds.size,'Con proyecto'],[needs.filter(n=>n.status==='Solucionada').length,'Solucionadas']].map(([n,t])=>`<div><strong>${n}</strong><span>${t}</span></div>`).join('')}</div><div class="intel-summary"><span><b>${actions.length}</b> actuaciones registradas</span><span><b>${projects.length}</b> proyectos registrados</span><span><b>${needs.filter(n=>n.nextAction).length}</b> con próxima acción</span><span><b>${needs.filter(n=>n.followUp).length}</b> con seguimiento programado</span></div>`;
}
function renderTerritory(){const db=getDB(),needs=arr(db,'needs'),leaders=arr(db,'leaders'),projects=arr(db,'projects'),actions=arr(db,'actions'),t=$('intelTerritorySelect')?.value;if(!$('intelTerritory'))return;if(!t){$('intelTerritory').innerHTML='<div class="intel-empty">Registre necesidades para habilitar esta ficha.</div>';return}const ns=needs.filter(n=>n.territory===t),ids=new Set(ns.map(n=>n.id)),ls=leaders.filter(l=>l.territory===t),ps=projects.filter(p=>p.territory===t||ids.has(p.needId)),as=actions.filter(a=>ids.has(a.needId));$('intelTerritory').innerHTML=`<div class="intel-mini-grid">${[[ns.length,'Necesidades'],[ns.filter(n=>n.priority==='Urgente').length,'Urgentes'],[ns.filter(n=>n.status==='En gestión').length,'En gestión'],[ns.filter(n=>n.status==='Solucionada').length,'Solucionadas'],[ls.length,'Líderes'],[ps.length,'Proyectos'],[as.length,'Gestiones']].map(([n,x])=>`<div class="intel-mini"><strong>${n}</strong><span>${x}</span></div>`).join('')}</div><div class="intel-list">${ns.slice(0,8).map(n=>`<div><b>${esc(n.code||'')}</b> ${esc(n.title||'')} <small>${esc(n.status||'')}</small></div>`).join('')||'<div>Sin necesidades registradas.</div>'}</div>`}
function printReport(type){const db=getDB(),all=arr(db,'needs'),leaders=arr(db,'leaders'),projects=arr(db,'projects'),actions=arr(db,'actions');let title='Diagnóstico Territorial de Girón',items=all;if(type==='territory'){const t=$('intelTerritorySelect')?.value||'';title=`Ficha Territorial · ${t}`;items=all.filter(n=>n.territory===t)}if(type==='management')title='Informe Ejecutivo de Gestión Territorial';const ids=new Set(items.map(n=>n.id));const act=actions.filter(a=>ids.has(a.needId));const pro=projects.filter(p=>!p.needId||ids.has(p.needId));const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{margin:18mm}body{font-family:Arial,sans-serif;color:#173757;line-height:1.45}h1{color:#073763;margin-bottom:4px}.sub{color:#60758a}.sum{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:20px 0}.box{border:1px solid #d8e3ee;border-radius:8px;padding:10px}.box b{display:block;font-size:22px;color:#073763}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{font-size:10px;padding:7px;border-bottom:1px solid #ddd;text-align:left}th{background:#eef5fb}</style></head><body><h1>${esc(title)}</h1><div class="sub">Matriz Maestra de Gestión Territorial para Girón · ${new Date().toLocaleDateString('es-CO')}</div><div class="sum"><div class="box"><b>${items.length}</b>Necesidades</div><div class="box"><b>${items.filter(n=>n.priority==='Urgente').length}</b>Urgentes</div><div class="box"><b>${items.filter(n=>n.status==='En gestión').length}</b>En gestión</div><div class="box"><b>${items.filter(n=>n.status==='Solucionada').length}</b>Solucionadas</div></div>${type==='management'?`<p><b>${act.length}</b> actuaciones · <b>${pro.length}</b> proyectos · <b>${leaders.length}</b> líderes registrados.</p>`:''}<table><tr><th>Código</th><th>Territorio</th><th>Necesidad</th><th>Sector</th><th>Prioridad</th><th>Estado</th><th>Próxima acción</th></tr>${items.map(n=>`<tr><td>${esc(n.code)}</td><td>${esc(n.territory)}</td><td>${esc(n.title)}</td><td>${esc(n.sector)}</td><td>${esc(n.priority)}</td><td>${esc(n.status)}</td><td>${esc(n.nextAction||'')}</td></tr>`).join('')}</table><script>window.print()<\/script></body></html>`;const w=window.open('','_blank');if(!w){alert('Permita ventanas emergentes para generar el informe.');return}w.document.write(html);w.document.close()}
function bind(){
 $('intelTerritorySelect')?.addEventListener('change',renderTerritory);
 if($('intelDiagnosisPdf'))$('intelDiagnosisPdf').onclick=()=>printReport('diagnosis');
 if($('intelTerritoryPdf'))$('intelTerritoryPdf').onclick=()=>printReport('territory');
 if($('intelManagementPdf'))$('intelManagementPdf').onclick=()=>printReport('management');
 document.querySelectorAll('[data-view="reports"]').forEach(b=>b.addEventListener('click',()=>setTimeout(render,0)));
 const quick=[...document.querySelectorAll('button[onclick*="reports"]')];quick.forEach(b=>b.addEventListener('click',()=>setTimeout(render,0)));
 window.addEventListener('storage',render);
 setTimeout(render,100);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
