/* Centro de Posicionamiento Territorial · v1.3.25
   Módulo independiente. No modifica app.js ni clasifica preferencias políticas. */
(()=>{'use strict';
const $=id=>document.getElementById(id), clean=v=>String(v??'').trim();
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function arr(k){try{return Array.isArray(db[k])?db[k]:[]}catch{return []}}
function territory(x){return clean(x.vereda||x.territory||x.zone||x.barrio||'Sin territorio')}
function relatedActions(n){return arr('actions').filter(a=>a.needId===n.id)}
function isSolved(n){return /solucion|resuelt|cumpl/i.test(clean(n.status))}
function fmt(v){if(!v)return '';try{return new Intl.DateTimeFormat('es-CO',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v))}catch{return v}}
function businessData(){try{return JSON.parse(localStorage.getItem('matriz_giron_businesses_v1')||'[]')}catch{return []}}
function commitments(){try{return JSON.parse(localStorage.getItem('matriz_giron_commitments_v1')||'[]')}catch{return []}}
function allTerritories(){const s=new Set();[...arr('needs'),...arr('leaders'),...arr('actions'),...businessData()].forEach(x=>{const t=territory(x);if(t&&t!=='Sin territorio')s.add(t)});return [...s].sort((a,b)=>a.localeCompare(b,'es'))}
function metrics(filter=''){
 const match=x=>!filter||territory(x)===filter;
 const needs=arr('needs').filter(match), actions=arr('actions').filter(a=>!filter||territory(a)===filter||needs.some(n=>n.id===a.needId));
 const leaders=arr('leaders').filter(match), biz=businessData().filter(match), solved=needs.filter(isSolved);
 return {territories:new Set([...needs,...actions,...leaders,...biz].map(territory).filter(x=>x!=='Sin territorio')).size,needs:needs.length,actions:actions.length,solved:solved.length,leaders:leaders.length,businesses:biz.length};
}
function renderKpis(){const m=metrics();$('footprintKpis').innerHTML=[['Territorios con actividad',m.territories],['Necesidades escuchadas',m.needs],['Gestiones registradas',m.actions],['Resultados / solucionadas',m.solved],['Empresas visibilizadas',m.businesses]].map(x=>`<div class="positioning-kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function fillTerritories(){const sel=$('positioningTerritory'),cur=sel.value;sel.innerHTML='<option value="">Todos los territorios</option>'+allTerritories().map(t=>`<option>${esc(t)}</option>`).join('');sel.value=cur}
function renderFootprint(){const selected=$('positioningTerritory').value, ts=selected?[selected]:allTerritories(),rows=ts.map(t=>{const m=metrics(t),score=m.needs+m.actions*2+m.solved*3+m.leaders+m.businesses*2;return {t,m,score}}).sort((a,b)=>b.score-a.score),max=Math.max(1,...rows.map(x=>x.score));$('territoryFootprint').innerHTML=rows.length?`<div class="footprint-list">${rows.map(x=>`<div class="footprint-row"><strong>${esc(x.t)}</strong><div class="footprint-bar"><i style="width:${Math.max(4,x.score/max*100)}%"></i></div><small>${x.m.actions} gestiones · ${x.m.solved} resultados · ${x.m.needs} necesidades</small></div>`).join('')}</div>`:'<p class="muted">Aún no hay actividad territorial registrada.</p>'}
function renderStories(){const mode=$('positioningStatus').value, selected=$('positioningTerritory').value;let needs=arr('needs').filter(n=>!selected||territory(n)===selected);if(mode==='results')needs=needs.filter(isSolved);if(mode==='active')needs=needs.filter(n=>!isSolved(n));needs.sort((a,b)=>String(b.created||'').localeCompare(String(a.created||'')));$('positioningStories').innerHTML=needs.length?needs.map(n=>{const acts=relatedActions(n);return `<div class="positioning-story"><div><h4>${esc(n.title||n.code||'Necesidad')}</h4><p>📍 ${esc(territory(n))} · Estado: <strong>${esc(n.status||'Sin estado')}</strong></p><p>${acts.length} gestión(es) relacionada(s)${n.competentEntity?' · '+esc(n.competentEntity):''}</p></div><button class="primary" type="button" data-story-id="${esc(n.id)}">📣 Preparar historia</button></div>`}).join(''):'<p class="muted">No hay registros que coincidan con este filtro.</p>'}
function draft(id){const n=arr('needs').find(x=>x.id===id);if(!n)return;const acts=relatedActions(n).sort((a,b)=>String(a.created||'').localeCompare(String(b.created||''))),last=acts[acts.length-1];const lines=[`📍 ${territory(n)}`,`\n${clean(n.title||'Necesidad del territorio')}`,clean(n.description)?`\nLa comunidad registró la siguiente situación: ${clean(n.description)}`:'',acts.length?`\nSe han registrado ${acts.length} gestión(es) de seguimiento en la Matriz.`:'',last&&clean(last.nextAction)?`\nÚltimo seguimiento registrado: ${clean(last.nextAction)}${last.nextDate?' ('+fmt(last.nextDate)+')':''}.`:'',clean(n.status)?`\nEstado actual: ${clean(n.status)}.`:'',clean(n.competentEntity)?`\nEntidad relacionada: ${clean(n.competentEntity)}.`:'',`\nSeguimos documentando el proceso y comunicaremos los avances verificables.`].filter(Boolean);$('positioningDraftText').value=lines.join('');$('positioningDraft').classList.remove('hidden');$('positioningDraft').scrollIntoView({behavior:'smooth',block:'start'})}

const PROPOSALS_KEY='matriz_giron_public_proposals_v1';
function proposals(){try{const x=JSON.parse(localStorage.getItem(PROPOSALS_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function saveProposals(x){localStorage.setItem(PROPOSALS_KEY,JSON.stringify(x))}
function renderProposals(){const box=$('positioningProposalList');if(!box)return;const list=proposals().sort((a,b)=>String(b.created||'').localeCompare(String(a.created||'')));box.innerHTML=list.length?'<h4>Propuestas guardadas</h4>'+list.map(x=>`<div class="positioning-proposal-item"><div><h4>${esc(x.title||'Propuesta')}</h4><p>${x.territory?'📍 '+esc(x.territory)+' · ':''}${esc((x.observation||'').slice(0,140))}</p></div><button type="button" class="secondary" data-proposal-delete="${esc(x.id)}">Eliminar</button></div>`).join(''):'<p class="muted">Aún no hay propuestas guardadas.</p>'}
function proposalText(){const title=clean($('proposalTitle')?.value),t=clean($('proposalTerritory')?.value),o=clean($('proposalObservation')?.value),idea=clean($('proposalIdea')?.value);return [title?`💡 ${title}`:'💡 Girón puede hacerlo mejor',t?`📍 ${t}`:'',o?`\nSituación observada: ${o}`:'',idea?`\nPropuesta: ${idea}`:''].filter(Boolean).join('\n')}
function openProposal(){const box=$('positioningProposal');if(!box)return;box.classList.remove('hidden');renderProposals();box.scrollIntoView({behavior:'smooth',block:'start'})}

function render(){if(!$('view-positioning'))return;renderKpis();fillTerritories();renderFootprint();renderStories();renderProposals()}
document.addEventListener('click',e=>{const v=e.target.closest('[data-pos-view]');if(v)showView(v.dataset.posView);const f=e.target.closest('[data-pos-filter]');if(f){if(f.dataset.posFilter==='results'){$('positioningStatus').value='results';renderStories();$('positioningStories').scrollIntoView({behavior:'smooth'})}else{$('positioningStatus').value='all';renderStories();$('positioningStories').scrollIntoView({behavior:'smooth'})}}if(e.target.closest('[data-pos-proposal]'))openProposal();const del=e.target.closest('[data-proposal-delete]');if(del){saveProposals(proposals().filter(x=>x.id!==del.dataset.proposalDelete));renderProposals()}const b=e.target.closest('[data-story-id]');if(b)draft(b.dataset.storyId)});
$('positioningProposalClose')?.addEventListener('click',()=>$('positioningProposal').classList.add('hidden'));
$('positioningProposalSave')?.addEventListener('click',()=>{const title=clean($('proposalTitle').value),observation=clean($('proposalObservation').value),idea=clean($('proposalIdea').value);if(!title||!observation||!idea){alert('Complete título, situación observada y propuesta.');return}const list=proposals();list.push({id:'prop-'+Date.now(),title,territory:clean($('proposalTerritory').value),observation,idea,created:new Date().toISOString()});saveProposals(list);['proposalTitle','proposalTerritory','proposalObservation','proposalIdea'].forEach(id=>$(id).value='');renderProposals();toast('Propuesta guardada')});
$('positioningProposalCopy')?.addEventListener('click',async()=>{const text=proposalText();if(!text){alert('Escriba primero la propuesta.');return}try{await navigator.clipboard.writeText(text);toast('Borrador copiado')}catch{alert('Seleccione y copie el texto manualmente.')}});
$('positioningTerritory')?.addEventListener('change',()=>{renderFootprint();renderStories()});$('positioningStatus')?.addEventListener('change',renderStories);$('positioningCloseDraft')?.addEventListener('click',()=>$('positioningDraft').classList.add('hidden'));$('positioningCopy')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('positioningDraftText').value);toast('Texto copiado')}catch{alert('Seleccione y copie el texto manualmente.')}});$('positioningGoPosition')?.addEventListener('click',()=>showView('position'));
const old=window.showView;window.showView=function(v){old(v);if(v==='positioning')render()};document.querySelector('[data-view="positioning"]')?.addEventListener('click',()=>setTimeout(render,0));window.addEventListener('storage',render);window.addEventListener('community-need-saved',render);setTimeout(render,250);
})();
